### ISSUE TITLE
CompressionInfo on AddFile does not work

### ISSUE THREAD

**Issue by kenkendk** [adamhathcock/sharpcompress#120]
When calling `WriteToStream` and supplying a `CompressionInfo` instance, it appears to be ignored.
Instead, the implementation reads the `CompressionInfo` instance passed to the constructor for the `ZipWriter`. By hacking it with reflection, I can change the `CompressionLevel` field on the original instance, and that allows me to change the compression level on a per-stream basis.

**Comment by adamhathcock** [comment]
Any chance for a PR?  I'll queue this up to look at.

**Comment by kenkendk** [comment]
Yes, there is now a PR.

There should also be a unittest for this, but I have not made that.

**Comment by adamhathcock** [comment]
Thanks!  I'll test it later.
