### ISSUE TITLE
Version in ZIP directory entries

### ISSUE THREAD

**Issue by tritao** [adamhathcock/sharpcompress#133]
Hi, some of Mono users reported compatibility problems with files produced by SharpCompress.

One of the tools that complains is MS Excel which refuses to load files produced by MS Open XML SDK.

Upon further debugging, this turns out to be caused by the version information written by SharpCompress.

One such issue has been already fixed by https://github.com/adamhathcock/sharpcompress/commit/c2b15b9c093ea80549fe0f6101c6c2c7241960b6

But it also needs to be fixed elsewhere in codebase.

You can backport or fix from: https://github.com/mono/mono/commit/77b034cbe78bfccfe4c1995152bd5562a1d69ef5

**Comment by adamhathcock** [comment]
Thanks, I'll do this.

**Comment by adamhathcock** [comment]
https://github.com/adamhathcock/sharpcompress/commit/ef8575a10756988d09e6e839e9171b60004d935d fixed version made by
