### ISSUE TITLE
Incorrect extraction of empty directory compressed with `System.IO.Compression`

### ISSUE THREAD

**Issue by zentron** [adamhathcock/sharpcompress#135]
When creating an zip file using the following standard powershell

```
Add-Type -Assembly System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($sourcedir, $zipfilename,  [System.IO.Compression.CompressionLevel]::Optimal, $false)
```

An empty folder has its file name encoded with a trailing `\`. 
Although `ZipFileEntry.cs` [correctly checks](https://github.com/adamhathcock/sharpcompress/blob/681b28f6545ec745bcd42754f019a7cde23ca8a4/SharpCompress/Common/Zip/Headers/ZipFileEntry.cs#L19) for trailing `/`, it doesn't consider this scenario. 
Digging through the 7zip code, it seems they are also aware of this problem and have explicitly coded around it, noting in their comments that
> .NET Framework 4.5 : System.IO.Compression::CreateFromDirectory() probably writes backslashes to headers? so we support that case

**Comment by zentron** [comment]
Above PR supports these zip archives

**Comment by adamhathcock** [comment]
Any chance for a Pull request?  Thanks!

**Comment by zentron** [comment]
sorry :) .. try check again.

**Comment by adamhathcock** [comment]
Thanks!
