### ISSUE TITLE
Problem publish app on store

### ISSUE THREAD

**Issue by a-iafrate** [adamhathcock/sharpcompress#141]
Hi,
i use your library on github but when i try to publish app on store i receive this error on validation

Error Found: The debug configuration test detected the following errors:
◦The binary SharpCompress.dll is built in debug mode.

so i need to compile from source code.

Can this bug be solved?

Thanks!

**Comment by RalphMack** [comment]
I'm running into the same issue in using it on our site. However, for the time being, I'm just getting "ahem" type emails from our ops guys. :) Any chance this can be addressed with a rebuild soon? I like making the ops guys really happy... Never irritate the quartermaster, etc., etc...

**Comment by adamhathcock** [comment]
I should fix this with using .NET Core RC2 https://github.com/adamhathcock/sharpcompress/pull/84

**Comment by adamhathcock** [comment]
I think this is fixed now.
