### ISSUE TITLE
Can you ship Non-Debug builds to Nuget?

### ISSUE THREAD

**Issue by RalphMack** [adamhathcock/sharpcompress#148]
The latest release, as previous releases, was built debug, as shown by the following ILDASM snippet:

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 **07 01** 00 00 00 00 )

Our release team scans our web apps for the use of any libraries compiled debug and sends us unhappy emails. :( Can future drops be delivered in release mode (full PDB is fine, but optimized)

**Comment by adamhathcock** [comment]
I need to.  Switching to the `dotnet` tooling next week and will look at using appveyor too.  I've neglicated the build too long.
