### ISSUE TITLE
Silverlight Version 0.12.0

### ISSUE THREAD

**Issue by kronic** [adamhathcock/sharpcompress#150]
Is silverlight supported?

**Comment by adamhathcock** [comment]
The windows phone version is under netstandard 1.0.  Do you need SL5?

**Comment by kronic** [comment]
Yes do need SL5.

**Comment by adamhathcock** [comment]
I think I did it now: https://www.nuget.org/packages/sharpcompress/0.12.1

**Comment by kronic** [comment]
Thank you so much. Very fast.
