### ISSUE TITLE
npm install (update) error

### ISSUE THREAD

**Issue by bercut497** [adamhathcock/sharpcompress#152]
Error message
> 
Ошибка
Failed to add reference. The package 'SharpCompress' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
>

Npm log
>
Выполняется попытка собрать информацию о зависимостях для пакета "SharpCompress.0.12.2" по отношению к проекту "X", нацеленному на ".NETFramework,Version=v4.5.2".
Сбор данных о зависимостях занял 864,4 ms
Выполняется попытка разрешить зависимости для пакета «SharpCompress.0.12.2» с использованием DependencyBehavior «Lowest»
Обнаружено одно неразрешенное ограничение зависимостей пакетов (или несколько) в существующем файле packages.config. Все ограничения зависимостей должны быть разрешены, чтобы добавить или обновить пакеты. Если эти пакеты обновляются, это сообщение можно пропустить, если же нет, следующие ошибки могут блокировать текущую операцию с пакетами: 'SharpCompress 0.12.1'
Разрешение данных о зависимостях заняло 0 ms
Разрешение действий для установки пакета «SharpCompress.0.12.2»
Разрешены действия для установки пакета «SharpCompress.0.12.2»
Получение пакета "SharpCompress 0.12.2" из "nuget.org".
Пакет «SharpCompress.0.12.1» удален из «packages.config»
"SharpCompress.0.12.1" успешно удалено из X
Добавление пакета «SharpCompress.0.12.2» в папку «C:\Users\YYY\Documents\Visual Studio 2015\Projects\X\packages»
Пакет «SharpCompress.0.12.2» добавлен в папку «C:\Users\YYY\Documents\Visual Studio 2015\Projects\X\packages»
Сбой установки. Идет откат…
В проекте «X» не существует пакета «SharpCompress.0.12.2»
В папке «C:\Users\YYY\Documents\Visual Studio 2015\Projects\X\packages» уже существует пакет «SharpCompress.0.12.1»
Пакет «SharpCompress.0.12.1» добавлен в «packages.config»
Удаление пакета «SharpCompress.0.12.2» из папки «C:\Users\YYY\Documents\Visual Studio 2015\Projects\X\packages»
Пакет «SharpCompress.0.12.2» удален из папки «C:\Users\YYY\Documents\Visual Studio 2015\Projects\X\packages»
Выполнение действий NuGet заняло 1,83 sec
Failed to add reference. The package 'SharpCompress' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
========== Готово ==========
Прошло времени: 00:00:03.0728039
>

**Comment by adamhathcock** [comment]
You're using .NET 4.5.2?

**Comment by bercut497** [comment]
yes.
`".NETFramework,Version=v4.5.2".`
SharpCompress version 0.12.1 work fine, but 0.12.2 not

**Comment by sickboy** [comment]
Same problem on .NET 4.6.
Probably: https://github.com/NuGet/Home/issues/3103

**Comment by adamhathcock** [comment]
Try this https://www.nuget.org/packages/sharpcompress/0.12.3

**Comment by sickboy** [comment]
@adamhathcock oh yes, that's it, thanks a lot!
(haven't checked for runtime issues yet, but adding works!)
