### ISSUE TITLE
Issue with update in Nuget for 0.12.2 only

### ISSUE THREAD

**Issue by RalphMack** [adamhathcock/sharpcompress#155]
I tried updating SharpCompress to 0.12.2 in NuGet and received the following error:

Failed to add reference. The package 'SharpCompress' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.	

I was able to successfully update to 0.12.1, though.

**Comment by adamhathcock** [comment]
I guess the PCL profile I added is no good.  I copied it from the Newtonsoft project.json too.

Are you full framework 4.5 or something?  There's like 3 different profiles on the package that could fit.

**Comment by RalphMack** [comment]
Yes - building with .NET Framework 4.5.1 - using the net45 version.

**Comment by adamhathcock** [comment]
Try this https://www.nuget.org/packages/sharpcompress/0.12.3

**Comment by RalphMack** [comment]
Thanks. That worked!
