### ISSUE TITLE
'SharpCompress' already has a dependency defined for 'System.Collections'

### ISSUE THREAD

**Issue by zeidmandevelopment** [adamhathcock/sharpcompress#157]
Cannot install

**Comment by zeidmandevelopment** [comment]
Required upgrade to latest nuget package manager

**Comment by kriswd40** [comment]
I'm running into this same issue and have the newest possible NuGet Package Manger installed with Visual Studio 2012. 

I guess it just isn't compatible with 2012 then?

**Comment by adamhathcock** [comment]
Nuget has been iterating quickly.  I can't recall if they released copies for VS2012.

Upgrade to VS2015.  Its free.

**Comment by kriswd40** [comment]
There isn't a newer version for VS 2012 available. I can't upgrade to 2015, this is for work and we're locked into 2012 unfortunately.
