### ISSUE TITLE
IArchiveEntry.OpenEntryStream() on 0.12.x on Xamarin crashes

### ISSUE THREAD

**Issue by ivanicin** [adamhathcock/sharpcompress#159]
0.11 works without the problem.

I've tested on Xamarin.iOS.

**Comment by adamhathcock** [comment]
Any chance for a call stack?

I guess it might have something to do with being netstandard vs not before.

**Comment by ivanicin** [comment]
I've decided to stick to the previous version. I am using it only for zip anyway and this new version requires several more NuGet packages to be installed which sounds like overkill for what I need to achieve.

I'll see to provide you with a call stack when I have the time as clearly you have helped me with making this great library, so I feel like I should contribute back, but as I gave up on updating it might not be immediate.

**Comment by adamhathcock** [comment]
I guess the issue has something to do with that Xamarin.iOS doesn't like the .NET Standard stuff I added.  Weird.

I still have targets for .net 3.5, 4.0 and 4.5 though.  Figuring out how to use one of those instead of .NET Standard might be an idea.

**Comment by adamhathcock** [comment]
I created 0.12.4 with a slightly different target but I doubt it will fix this for you

**Comment by ivanicin** [comment]
Fixed now in 0.18
