### ISSUE TITLE
SharpCompress v0.12.4 NuGet package causes payload errors when building with Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by MaxRis** [adamhathcock/sharpcompress#169]
Hello,

After I have updated Visual Studio to the latest Update 3 (Anniversary edition) and tried to build Universal application project, where SharpCompress NuGet package is used along with Microsoft.NETCore.UniversalWindowsPlatform v.5.1.0, I've started getting following errors during build:

Error		Payload contains two or more files with the same destination path 'Microsoft.Win32.Primitives.dll'. Source files: 
C:\Users\Admin\.nuget\packages\Microsoft.Win32.Primitives\4.0.0\lib\dotnet\Microsoft.Win32.Primitives.dll
C:\Users\Admin\.nuget\packages\runtime.win.Microsoft.Win32.Primitives\4.0.1\runtimes\win\lib\netstandard1.3\Microsoft.Win32.Primitives.dll

and similar errors for assemblies: System.Diagnostics.Tools.dll , System.Globalization.Calendars.dll, System.Threading.Timer.dll and System.Net.Sockets.dll

Such errors happens just with empty UWP project created with latest Visual Studio and with added SharpCompress NuGet package ialong with Microsoft.NETCore.UniversalWindowsPlatform v.5.1.0

I'm not sure how can I handle this issue correctly, it will be great if you will able to provide some suggestions regarding this,

Thank you,
Max

**Comment by adamhathcock** [comment]
Looks like UWP 5.1.0 is really old and drags in old dependencies.

5.2.2 is what you want: https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/5.2.2

**Comment by MaxRis** [comment]
Thank you very much for the answer!
Just moment ago I have solved dependencies issue by embedding all sources directly into the project.

Yes, with 5.2.2 it seems work fine! (but one another lib complain with 5.2.2 =) )
