### ISSUE TITLE
VS 2015 cannot compile it!

### ISSUE THREAD

**Issue by XuTpuK** [adamhathcock/sharpcompress#170]
Why you distribute your code as a "nejuzabel'noe govno"? (in english means "strange code")
I tried to open it in VS 2015 and got this:
"The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found"

Where you get this "Microsoft.DotNet.Props" and why you need it at all? Isn't VS has Properties?

**Comment by adamhathcock** [comment]
It's cross platform https://www.microsoft.com/net/core/platform
