### ISSUE TITLE
Examples out of date

### ISSUE THREAD

**Issue by gaffo** [adamhathcock/sharpcompress#171]
Examples at https://github.com/adamhathcock/sharpcompress/wiki/API-Examples

Say 

using (var zipWriter = WriterFactory.Open(ArchiveType.Zip, zip))

However newest version takes 3 arguments.

**Comment by adamhathcock** [comment]
Should do this along side an options refactor mentioned in https://github.com/adamhathcock/sharpcompress/issues/172

**Comment by adamhathcock** [comment]
Hopefully this covers it: https://github.com/adamhathcock/sharpcompress/blob/master/USAGE.md

Can make PRs!
