### ISSUE TITLE
Entry.WriteToDirectory crashes on a particular entry of a particular 7Zip archive

### ISSUE THREAD

**Issue by Tyrrrz** [adamhathcock/sharpcompress#176]
Archive in question: http://www.tyrrrz.me/dl/test.7z

The following code:

    using (var archive = ArchiveFactory.Open(archiveFilePath, Options.None))
    {
        foreach (var entry in archive.Entries)
        {
            entry.WriteToDirectory(destinationDirectory, ExtractOptions.ExtractFullPath | ExtractOptions.Overwrite);
        }
    }

...raises "Method not supported" exception on all entries in the following folder: "sound\weapons" (the rest unpack fine).

I have tried the code above, using a reader, instead of iterating over entries, all to the same result.

**Comment by adamhathcock** [comment]
Hah!  Those entries are compressed with Deflate and for some reason it just wasn't implemented.  Easy to do.
