### ISSUE TITLE
Build archive in memorystream while keeping it open

### ISSUE THREAD

**Issue by zaryk** [adamhathcock/sharpcompress#177]
Is there a way to build archive in memorystream while keeping it open?  The below way seems to create it, but once returned, it is not open.  I also looked at the ZipArchive constructor where there is an option to keep it open, but passing in the stream said that it could not find zip headers.  I just need a regular zip.  I know the supported formats for streams are the below, so does that mean this will not work?

BZip2Stream	Both
GZipStream	Both
DeflateStream	Both
LZMAStream	Both
PPMdStream	Both

`
        internal virtual MemoryStream InternalDownloadStream(int offset, int readSize)
        {
            var archive = ZipArchive.Create();
            archive.AddAllFromDirectory(directoryInfo.FullName, "*.*", SearchOption.AllDirectories);
            var stream = new MemoryStream();
            if (offset == 0 && readSize == 0)
            {
                archive.SaveTo(stream, new CompressionInfo() { DeflateCompressionLevel = Core.SharpCompress.Compressor.Deflate.CompressionLevel.Default, Type = CompressionType.None });
                return stream;
            }
            else
            {
                throw new NotImplementedException();
            }
        }
`

**Comment by adamhathcock** [comment]
You mean you want an option on the 'SaveTo' method on WritableArchives to leave the stream open?

**Comment by adamhathcock** [comment]
Also, you need to reset the `MemoryStream` position back to 0 to make it usable too.

**Comment by zaryk** [comment]
- You mean you want an option on the 'SaveTo' method on WritableArchives to leave the stream open?

I suppose.  It doesn't really matter where.

- Also, you need to reset the MemoryStream position back to 0 to make it usable too.

I am sure I tried that as well, but maybe not.  Will get back to you.

**Comment by adamhathcock** [comment]
I thought the options got passed down.  Anyway, I've just refactored the way options work for the next release.  Maybe it will be more clear.

**Comment by adamhathcock** [comment]
https://github.com/adamhathcock/sharpcompress/blob/master/USAGE.md#create-zip-archive-from-all-files-in-a-directory-and-save-in-memory

**Comment by zaryk** [comment]
cool thanks!  I will check it out.
