### ISSUE TITLE
Unnecessary allocation in ZipWriter?

### ISSUE THREAD

**Issue by UnknownShadow200** [adamhathcock/sharpcompress#182]
Noticed this line in ZipWriter.cs
```CSharp
private readonly PpmdProperties ppmdProperties = new PpmdProperties();
```
ends up calling Allocator.Start() which allocates a 16 megabyte byte array.

I assume this field is only meant to be assigned when PPMd compression type?

**Comment by adamhathcock** [comment]
Yeah, looks bad.  I'll look into fixing that shortly

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/sharpcompress/0.13.1
