### ISSUE TITLE
Null reference when disposing a Volume class

### ISSUE THREAD

**Issue by JasonBro** [adamhathcock/sharpcompress#187]
There's a new bit of code in the SharpCompress.Common.Volume class that causes a null exception when ReaderOptions is null (which it is by default). 

Workround: Add a ReaderOptions in the Open(Stream, ReaderOptions) call.

        public void Dispose()
        {
            if (!ReaderOptions.LeaveStreamOpen && !disposed)
            {
                actualStream.Dispose();
                disposed = true;
            }
        }

**Comment by adamhathcock** [comment]
Oh no.  Thanks for reporting this.  I'll fix it.

**Comment by JasonBro** [comment]
I know that feeling! I would have fixed it myself with a pull request, but
there might be other places that were changed as well.

I'm in no rush for the fix and it only took 2 minutes to find a work round.
Thanks for creating a great library.

Cheers

Jason

**Comment by adamhathcock** [comment]
What archive format are you using?  I was hoping that the options would never be null by the time it got to the `Volume` class.

**Comment by JasonBro** [comment]
This is the bit of code:-

using (var stream = await file.OpenAsync(FileAccess.Read))
{
using (var archive = SevenZipArchive.Open(stream))
{
...

**Comment by adamhathcock** [comment]
Thanks, found it.  Also found another null issue while reviewing the code paths.

I wish I could mock test this stuff but not possible with this code :(

**Comment by JasonBro** [comment]
Besides, no matter how much you test it, someone will come up with ways of
using it you'd not thought of!

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/sharpcompress/0.13.1

**Comment by JasonBro** [comment]
Perfect! Thanks for your fast response. :-)
