### ISSUE TITLE
Short truncated decompress by BZip2Stream

### ISSUE THREAD

**Issue by kekyo** [adamhathcock/sharpcompress#19]
Hi,  I'm tested very large bzip2'ed stream decompress by BZip2Stream.

```
using (var fs = new FileStream(@"D:\planet-latest.osm.bz2", FileMode.Open, FileAccess.Read, FileShare.Read))
{
    using (var cs = new BZip2Stream(fs, CompressionMode.Decompress))
    {
        using (var ts = new FileStream(@"D:\pp.osm", FileMode.Create, FileAccess.ReadWrite, FileShare.Read))
        {
            cs.CopyTo(ts);
            ts.Close();
        }
    }
}
```

Data is OpenStreetMap's Planet.osm.bz2. (size=36GB)
Outputted pp.osm size is just 900000 bytes, of course may result 500GB over.

How can I decompress this file?
Thanks.

**Comment by adamhathcock** [comment]
I think this is the same as https://github.com/adamhathcock/sharpcompress/issues/166 closing this
