### ISSUE TITLE
ArgumentOutOfRangeException on Zip expansion

### ISSUE THREAD

**Issue by dkekesi** [adamhathcock/sharpcompress#194]
I get the following exception when expanding a certain Zip archive:

System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
Parameter name: value
   at System.IO.MemoryStream.set_Position(Int64 value)
   at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader)
   at SharpCompress.Common.Zip.SeekableZipHeaderFactory.GetLocalHeader(Stream stream, DirectoryEntryHeader directoryEntryHeader)
   at SharpCompress.Common.Zip.SeekableZipFilePart.LoadLocalHeader()
   at SharpCompress.Common.Zip.SeekableZipFilePart.GetCompressedStream()
   at SharpCompress.Archives.IArchiveEntryExtensions.WriteTo(IArchiveEntry archiveEntry, Stream streamToWriteTo)

Can you look into what the problem may be? Other programs can expand the Zip. The file itself is merely 300K in size.
Thanks.

**Comment by adamhathcock** [comment]
Need an example ZIP to see the problem really.

**Comment by dkekesi** [comment]
The zip contains confidential information. Can you send me an email address that I can send the file to?

**Comment by dkekesi** [comment]
Do you have any update on this? There are other files again with the same issue. If you can give me a mail address then I can send you the file.

**Comment by adamhathcock** [comment]
I haven't looked into this at all and likely won't soon.  Sorry.

I assume other things actually do open this zip?  DotNetZip ought to have he same issue.  You could try the built in zip stuff in .NET

**Comment by dkekesi** [comment]
Heavy sigh... Thanks, anyway.
    
    On 2017. 04. 08. 8:27, Adam Hathcock wrote:
    
      I haven't looked into this at all and likely won't soon. Sorry.
      I assume other things actually do open this zip? DotNetZip
        ought to have he same issue. You could try the built in zip
        stuff in .NET
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adamhathcock/sharpcompress","title":"adamhathcock/sharpcompress","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adamhathcock/sharpcompress"}},"updates":{"snippets":[{"icon":"PERSON","message":"@adamhathcock in #194: I haven't looked into this at all and likely won't soon.  Sorry.\r\n\r\nI assume other things actually do open this zip?  DotNetZip ought to have he same issue.  You could try the built in zip stuff in .NET"}],"action":{"name":"View Issue","url":"https://github.com/adamhathcock/sharpcompress/issues/194#issuecomment-292698597"}}}

**Comment by dkekesi** [comment]
It seems that version 0.17.1 can cope with the problematic file. I think this case can be closed.
