### ISSUE TITLE
Common.ExtractOptions, gone?

### ISSUE THREAD

**Issue by viniliuti** [adamhathcock/sharpcompress#196]
When migrating my project and adding it to TFS I updated the version I was using, from 10.3 to 14.0 through Nugget pack system.
Once builded, came a lot of errors and the missing ExtractOptions I didn't find any way to correct it but installing the old 10.3 version.
Examples from Wiki still uses the ExtractOptions, so what could be the new way for extracting files?

**Comment by adamhathcock** [comment]
You can figure this out by looking at the tests.  I'll update the wiki sometime.

**Comment by viniliuti** [comment]
Will check
Thanks!
