### ISSUE TITLE
entry.WriteToDirectory

### ISSUE THREAD

**Issue by Ethan872** [adamhathcock/sharpcompress#204]
This method is missing?

**Comment by aximili** [comment]
I guess the extract RAR example here is wrong https://github.com/adamhathcock/sharpcompress/blob/master/USAGE.md

The Archive example here works:
https://sharpcompress.codeplex.com/wikipage?title=Composite%20API%20Examples

**Comment by adamhathcock** [comment]
@Ethan872 It's only missing if you're on a platform that doesn't support File operations like phones.

@aximili no, that code sample is wrong unless you're on an old version.
