### ISSUE TITLE
How Can i Get File Content as Byte array or as stream from Entries 

### ISSUE THREAD

**Issue by ljdhameliya** [adamhathcock/sharpcompress#221]
Hello,
 How can i get filecontent of extract file in entry 
 var archive = ArchiveFactory.Open("abc.zip");
              
                foreach (var entry in archive.Entries)
                    {
                    // how can get byte array or stream of file form entry 
                    }
thanks in advance

**Comment by adamhathcock** [comment]
Look at the tests
