### ISSUE TITLE
Multi-volume Rar streams

### ISSUE THREAD

**Issue by krvi** [adamhathcock/sharpcompress#224]
I'm attempting to read the contents of multi-volume Rar archive. The archive is never written to disk so I need to read them as streams. I do the following steps.
1: Declare a dictionary, rather than List, simply for ease of ordering/sorting.
`var rd = new Dictionary<string, Stream>();`
2: Populate the dictionary. 
2.5: Ensure that the streams are ordered. For example:
_file.part1.rar
file.part2.rar
file.part2.rar_
or
_file.rar
file.r00
file.r01_
3: Open archive
`var ra = RarArchive.Open(rd.Values.AsEnumerable());`

From what I've [read](http://sharpcompress2.rssing.com/chan-6339576/all_p3.html) it is supposed to work with this procedure. However, it does not work.
`ra.WriteToDirectory(@"C:\test\");` Produces nothing and neither does
```
foreach (var e in ra.Entries)
    {
          e.WriteToDirectory(@"C:\test\");
          //or
          var fs = new FileStream(@"C:\test\" + e.Key, FileMode.Create, FileAccess.Write);
          e.WriteTo(fs);
          fs.Close();
    }
```
If I open the archive with only the first volume with ArchiveFactory
`var ra = ArchiveFactory.Open(rd.Values.First());`
It works, for the _whole_ files _in the first volume_. I can successfully use them and write them to disk.

What am I missing to be able to read the whole archive? Is this intended behavior or a bug?

**Comment by adamhathcock** [comment]
It does work.  Here's a relevant test: https://github.com/adamhathcock/sharpcompress/blob/master/test/SharpCompress.Test/Rar/RarArchiveTests.cs#L191

I would think it's because `Dictionary.Values.GetEnumerator` doesn't return any guaranteed order.

**Comment by krvi** [comment]
Thanks for the reply. My issue was a bit more embarrassing though, the streams' position was at the end.
It works fine now, with the generic collections that I have tried, List/Dictionary/SortedDictionary/OrderedDictionary etc. Extracts even if it's out of order! but split-files are understandably split, heh.
Thanks for a nice library.
