### ISSUE TITLE
Extract rar with password does not work

### ISSUE THREAD

**Issue by HamzaHizam** [adamhathcock/sharpcompress#228]
In my app I need to Extract rar with password but I cant find any thing in google help me.
- I tried like that here [https://github.com/adamhathcock/sharpcompress/issues/25](url)
but I got error in RarArchive.Open that say
**Error	2	No overload for method 'Open' takes '3' arguments	C:\Users\hamza\Documents\Visual Studio 2008\Projects\TryToUnRarfiFles\TryToUnRarfiFles\Form1.cs	40	38	TryToUnRarfiFles
**
-And I tried like that here [https://github.com/adamhathcock/sharpcompress/issues/213](url)
but I got error again in  --new ReaderOptions()--  and said
**Error	2	The type or namespace name 'ReaderOptions' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\hamza\Documents\Visual Studio 2008\Projects\TryToUnRarfiFles\TryToUnRarfiFles\Form1.cs	130	64	TryToUnRarfiFles**
...
Please if any one can help me ...

**Comment by adamhathcock** [comment]
Did you try looking at the options or tests instead of copy/pasting other things?

You're likely looking at old samples as the API surface changed

**Comment by HamzaHizam** [comment]
Yes I think that. but I need any way to Extract rar with password may you help..

**Comment by adamhathcock** [comment]
Just look at the tests.  Dig a little.

https://github.com/adamhathcock/sharpcompress/blob/master/test/SharpCompress.Test/Rar/RarArchiveTests.cs#L16
