### ISSUE TITLE
Cannot Extract TarArchive - no entries found!

### ISSUE THREAD

**Issue by Beatsleigher** [adamhathcock/sharpcompress#229]
I have a simple re-index functionality, and some older archives (application structure) are stored as .tar.gz archives.
The tars are unzipped fine, and they are detected as .tar files within the application, however no entries are found!

I've opened the file in WinRAR, and there most definitely are files within the archive, and they can be extracted with WinRAR.

I'm using VS 2017, C#7 with .Net framework 4.6,
Windows 10 and Mono 4.6

![winrar_entries](https://cloud.githubusercontent.com/assets/3124521/25739879/23f45ec2-3184-11e7-92d4-387ffa3a3e79.PNG)
![lib_entries](https://cloud.githubusercontent.com/assets/3124521/25739880/23f560b0-3184-11e7-96bc-75cfb590f9fc.PNG)

**Comment by adamhathcock** [comment]
I'm not going to be able to solve this without a sample file.

I recommend trying to debug this yourself as Tar is a simple format.  Maybe at least to give a hint about what's going wrong.

**Comment by Beatsleigher** [comment]
Sadly I can't give you the files in question, otherwise I would have (privacy and confidentiality).
I'm currently attempting to debug the solution myself. This issue was more a post to mention an issue with the library, and possibly add a solution for others. 

Currently, I'm determining whether an issue occurred with my GZ-uncompressor (unlikely, as it works fine with other file types, but then again, unlikely doesn't mean impossible).

**Comment by adamhathcock** [comment]
Why are you using a separate GZ decompressor rather than SharpCompress's?  I'm asking as I'm always looking to improve implementations.

**Comment by Beatsleigher** [comment]
The method I implemented has simpler usage, and doesn't use as many resources.
I'm using the un-/compressor provided by .Net, and simply passing a FileInfo and a ref MemoryStream.
I'm passing multiple thousand files, sometimes several hundred megabytes in size, and I can't afford to wait for the GC to come along and clear all those objects - I'd rather have one stream, and re-use it.

I've tested both SharpCompress' methods, and mine, and so far mine has proven to be less resource-hungry in our scenarios.

Also, confirmed it's not to do with my uncompressor. No matter how I extract the tar archive, it always shows empty within the objects.
TotalSize is also apparently null.

The thing that disturbs me the most at this point, is these tar archives were generated with SharpCompress in the first place.

**Comment by Beatsleigher** [comment]
`/// <summary>
        /// Uncompresses a gz file.
        /// </summary>
        /// <param name="filePath">The file path.</param>
        /// <param name="memStream">The memory stream.</param>
        void UncompressGzFile(string filePath, ref MemoryStream memStream) {
            using (var fStream = new FileStream(filePath, FileMode.Open))
            using (var zipStream = new GZipStream(fStream, CompressionMode.Decompress, false)) {
                zipStream.CopyTo(memStream = new MemoryStream());
                memStream.Position = 0; // Set position to beginning to prevent weird errors from happening throughout the application.
            }
        }`

That's my uncompressing code. You could change the parameters to decide whether to compress or decompress a stream. It's fairly simple, but very effective. 

I think I've narrowed the issue down to the position of the stream somehow moving to the end.
I'm just about to run another test.

**Comment by Beatsleigher** [comment]
I've saved the extracted tar file to the disk, and opened it in a hex editor, I'm not too familiar with tar headers, but this seems almost correct:
![tar_header](https://cloud.githubusercontent.com/assets/3124521/25741352/aae8181e-318a-11e7-8979-83772744c451.PNG)

**Comment by Beatsleigher** [comment]
I seem to have fixed the issue.
Somehow, creating a new memory stream with the buffer of the "old" memory stream has solved the issue.
Perplexing, seeming as the memory streams are virtually identical.

**For others observing this behavior, first attempt to create a new memory stream with the buffer of the previous stream - that has solved this issue for me.**
