### ISSUE TITLE
Invalid Rar Header: 3

### ISSUE THREAD

**Issue by KazeSenoue** [adamhathcock/sharpcompress#239]
Hey, could I get a hand please? I'm trying to extract this one rar file, but when opening it with `RarArchive.Open()` I get the exception `Invalid Rar Header: 3`. I can extract it no problem with both WinRAR and 7Zip, so I believe there's something I can do to be able to extract this file. Any ideas?

Code:
```
using (var archive = RarArchive.Open(Path.Combine("Temp/", file)))
{
    foreach (var entry in archive.Entries.Where(entry => !entry.IsDirectory))
    {
        entry.WriteToDirectory("Temp2/", new ExtractionOptions()
        {
            ExtractFullPath = true,
            Overwrite = true
        });
    }
}
```

File: [patch.zip](https://github.com/adamhathcock/sharpcompress/files/1022368/patch.zip)

**Comment by adamhathcock** [comment]
Might be a RAR5 file.  The format changed and I haven't implemented it.

**Comment by KazeSenoue** [comment]
Ah, ok. Any ETAs on when that'll be implemented?

**Comment by adamhathcock** [comment]
Oh wait, you're giving a zip file and using `RarArchive.Open` on it?  That's not going to work.

**Comment by adamhathcock** [comment]
No, no ETA

**Comment by KazeSenoue** [comment]
Oh, you're right. I didn't realize it was a zip and not a rar. Maybe make that exception a bit clearer in the future? Either way, thanks for the help :)

**Comment by adamhathcock** [comment]
Well, it's plenty clear.  It was an invalid rar header because it's a zip file :)

**Comment by KazeSenoue** [comment]
Fair enough
