### ISSUE TITLE
AddAllFromDirectory not found

### ISSUE THREAD

**Issue by CheetahChrome** [adamhathcock/sharpcompress#240]
Installed the latest version 0.16.1 via Nuget. Took the first example, then pulled in `using SharpCompress.Archives.Zip` and it fails stating `AddAllFromDirectory` does not exist. Also `SaveTo` exists but doesn't take a string but a stream. First example fails....

Is there an extension namespace to bring in? 

Using .Net 3.5 which may be applicable. 

--- Second example

Took second example:

```
using (var zip = File.OpenWrite("C:\\test.zip"))
using (var zipWriter = WriterFactory.Open(ArchiveType.Zip, zip))
{
     foreach (var filePath in filesList)
     {
        zipWriter.Write(Path.GetFileName(file), filePath);
     }
}
```

and `Open` needs the stream, which is fine and fixable,  but then the third parameter of `WriterOptions` is not an enum; and it is unclear how it needs to be used.

**Comment by adamhathcock** [comment]
The code is here https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Archives/IWritableArchiveExtensions.cs

You need `SharpCompress.Archives`
