### ISSUE TITLE
If I create a zip file that contain zero size files,the Windows 10 Explorer build-in zip viewer can't uncompress it.

### ISSUE THREAD

**Issue by yinyue200** [adamhathcock/sharpcompress#243]
English is not my native language; please excuse typing errors.
Thanks

**Comment by adamhathcock** [comment]
Couple questions:  does anything else open it?  Maybe Windows 10 just doesn't like zero byte files.  

Can you show me your code?

**Comment by yinyue200** [comment]
@adamhathcock 7zip can open it.
sample code:https://github.com/yinyue200/sharpcompressdemo

Here is the error message.The screenshot is created by the Chinese version of Windows 10, but I hope it can be useful.
![tim 20170530214354](https://cloud.githubusercontent.com/assets/13848771/26586327/6f5a3d76-4581-11e7-9110-78d7779a27a7.png)
[a.zip](https://github.com/adamhathcock/sharpcompress/files/1038511/a.zip)

**Comment by adamhathcock** [comment]
If you create a file like this with a zero byte entry in another application, can Windows 10 open that?

I'm saying it might be a failing (or security check) for Windows 10.

**Comment by yinyue200** [comment]
@adamhathcock I can create a zip file that contain zero size file by 7zip. And it can be opened by Windows 10. Here is the file.
[a.zip](https://github.com/adamhathcock/sharpcompress/files/1038536/a.zip)

**Comment by yinyue200** [comment]
@adamhathcock Sharpziplib can't open the file that created by sharpcompress and contain zero file too  
I hope it can help you.

**Comment by adamhathcock** [comment]
I think it's because the entry is still marked as compressed even though it's zero bytes.  The 7Zip created file you gave has the entry marked as CompressionMethod = None.

I guess that's the difference.  I don't want to make SharpCompress smart enough to recognize that.  That's a user responsibility I think.

**Comment by adamhathcock** [comment]
Found a bug while reviewing this though: https://github.com/adamhathcock/sharpcompress/pull/249

**Comment by yinyue200** [comment]
@adamhathcock Thanks
