### ISSUE TITLE
when I create a zip file to a seekable stream that contain some content,the zip content overrides the original content

### ISSUE THREAD

**Issue by yinyue200** [adamhathcock/sharpcompress#244]
English is not my native language; please excuse typing errors.
Thanks

**Comment by adamhathcock** [comment]
I don't think I understand what you mean on this one.  What do you mean "orderless stream?"

**Comment by yinyue200** [comment]
@adamhathcock it means zip content overrides the original content

**Comment by adamhathcock** [comment]
That sounds like a desired behavior.  You might need to give me a code sample.

**Comment by yinyue200** [comment]
`using (var file = System.IO.File.Create("D:\\a.zip"))
            {
var bt=System.Text.Encoding.UTF8.GetBytes("https://github.com/adamhathcock/sharpcompress/issues/244");
                file.Write(bt,0,bt.Length);
                using (var zw = new SharpCompress.Writers.Zip.ZipWriter(file, new SharpCompress.Writers.Zip.ZipWriterOptions(SharpCompress.Common.CompressionType.Deflate)))
                {
                    zw.WriteToStream("a",new SharpCompress.Writers.Zip.ZipWriterEntryOptions()).Dispose();
                }
}`
And the file will not start with the URL.
@adamhathcock

**Comment by adamhathcock** [comment]
Thanks for finding this.  It was a bug introduced with the Zip64 writing support.
