### ISSUE TITLE
WinZipAes no longer supported on .NET 3.5

### ISSUE THREAD

**Issue by dbaumber** [adamhathcock/sharpcompress#250]
On .NET 3.5, working with ZIP archives that use WinZipAes are now throwing a NotSupportedException() from ZipHeaderFactory.LoadHeader(). The comment indicates that this is intended for Silverlight and Windows Phone, but the build configuration specifies this for .NET 3.5 as well. WinZipAes protected ZIP files used to work (with some issues) prior to version 0.16.0.

**Comment by adamhathcock** [comment]
Should be in https://www.nuget.org/packages/sharpcompress/0.16.2
