### ISSUE TITLE
How to manage long path issue of windows

### ISSUE THREAD

**Issue by talk2sunil83** [adamhathcock/sharpcompress#259]
Hi there,
While unzip I encountered the message "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters." I know the reason of issue but is there any inbuilt way/option to handle it.

Thanks

**Comment by adamhathcock** [comment]
This is a likely a framework issue.  Long path support came in 4.6.2 https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/

Give me a stack trace of you think otherwise.

**Comment by talk2sunil83** [comment]
Hi Adam,
Thank you for information.

--Sunil

**Comment by Veiintc** [comment]
I want to use it in .net3.5. Is there any solution?
My English is not very good, what is wrong, please forgive me^_^

**Comment by adamhathcock** [comment]
You have to manage the paths yourself to ensure it’s less than 260 characters.  Nothing else can be done.

**Comment by Veiintc** [comment]
Thank you for this .Looks like I have to manage the paths.
Thanks again for your reply^_^
