### ISSUE TITLE
how to Archive Zip file from FromDirectory

### ISSUE THREAD

**Issue by why5684784** [adamhathcock/sharpcompress#260]
your Example said
`using (var archive = ZipArchive.Create())
{
	archive.AddAllFromDirectory(@"C:\source");
	archive.SaveTo(@"C:\new.zip");
}`
[https://github.com/adamhathcock/sharpcompress/wiki/API-Examples#archive-random-access-api-example]
but,I don't file the AddAllFromDierctory in ZipArchive.Create()

**Comment by adamhathcock** [comment]
It's an extension method.  Search the source.
