### ISSUE TITLE
No net40 target after 0.15.2

### ISSUE THREAD

**Issue by catester** [adamhathcock/sharpcompress#273]
Is there a reason why net40 target was removed? I see that there is no specific code for net45 so I guess net40 can also be included in nuget package.

**Comment by adamhathcock** [comment]
Microsoft doesn’t support net40 anymore.  I put net45 on purely to make the net standard compatibility easier to manage.  They still support net35 so that’s why that is there.

**Comment by catester** [comment]
Thanks for the reply. Yes I know but I think net40 is still widely used, most essential libraries still have it in their nuget package but I understand it's hard to manage all this different compatibility levels. I could also use net35 of course, but I prefer the more performant Directory.EnumerateFiles over Directory.GetDirectories (net35).

Nevermind the issue, I can still build for net40 when I add it to TargetFrameworks in csproj.

**Comment by adamhathcock** [comment]
It doesn’t bother me if you want to add net40 in a PR.

Having net35 is already a pain because of mono deprecating it.
