### ISSUE TITLE
Add Entry.GetKeyBytes() method

### ISSUE THREAD

**Issue by xupefei** [adamhathcock/sharpcompress#277]
Related to #163, #261 and #266.

Since the string encoding in Zip archive is such a great pain, is it possible to provide a `byte[]` which contains raw bytes of file name without decoding, so the user can employ other libs (e.g. [Chardet](https://github.com/errepi/ude)) to process it later?

If you think it's okay, I am happy to do it and then open a PR :-)

**Comment by adamhathcock** [comment]
Yeah, you should be able to do that.  It’s just raw bytes before I try to do something.

A PR with Chardet sounds cool

**Comment by adamhathcock** [comment]
Using some custom decoder function on ArchiveEncoding with the changes in this PR would be good: https://github.com/adamhathcock/sharpcompress/pull/274

**Comment by adamhathcock** [comment]
Solved with 0.18

**Comment by xupefei** [comment]
Just to mention, there is a better and newer library for detecting encoding: https://github.com/CharsetDetector/UTF-unknown :P

**Comment by adamhathcock** [comment]
Hah.  I had already started but this seems better and exactly the same as I'd do.
