### ISSUE TITLE
If a zip file contains other zip file, ReaderFactory can't iterator all entry

### ISSUE THREAD

**Issue by szx9231** [adamhathcock/sharpcompress#285]
Sorry, it is not a bug.

**Comment by adamhathcock** [comment]
I don't think I understand.  I think your diagram isn't marked down properly.

Do you have b.zip inside a.zip?  You'll have to make a new zipreader for b.zip's stream coming out of the entry in a.zip

**Comment by szx9231** [comment]
Sorry, my diagram format is broken.
I capture a pic, it likes below:
![image](https://user-images.githubusercontent.com/7289036/29237852-de3a18f8-7f59-11e7-920e-c1b1127dfd8c.png)

There are two zip files in test.zip, (a.zip and b.zip)
![image](https://user-images.githubusercontent.com/7289036/29237886-681f66a4-7f5a-11e7-84e1-8f08f02398d9.png)
There is only 1.txt in a.zip and 2.txt in b.zip.
![image](https://user-images.githubusercontent.com/7289036/29237899-960606f4-7f5a-11e7-97ad-ed78fe14bbd3.png)

![image](https://user-images.githubusercontent.com/7289036/29237896-8ae64e28-7f5a-11e7-92e3-034591f2e338.png)

But i found i can not read the file 2.txt in b.zip.


Thanks~
