### ISSUE TITLE
Nuget fails to install

### ISSUE THREAD

**Issue by ivanicin** [adamhathcock/sharpcompress#286]
I believe this is the same error with description on how to fix it: https://github.com/onovotny/ReferenceGenerator/issues/4

In general you get error message like this:
`One or more projects are incompatible with UAP,Version=v10.0. Project xxx is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm.`

The solution from the user side is to edit project.json and change uap from 10.0 to 10.0.x, but it would be better if the nuget is fixed.

**Comment by adamhathcock** [comment]
That fix is about 2 years old.  project.json is way dead now.

This might be more applicable to you: https://stackoverflow.com/questions/38315273/cannot-reference-net-core-library-from-uwp

**Comment by ivanicin** [comment]
Adam, thanks for the link.

As said the problem is fixed for me after editing project.json. Some nugets can install, SharpCompress can't. If you feel like it is OK you can close the issue, I just wanted to report on the possible problem some people might be facing.

**Comment by adamhathcock** [comment]
project.json is deader than dead.  You should be using .NET Core RTM tooling and probably even 2.0 now as it was just released.  This fix won't work for others.
