### ISSUE TITLE
There is no proper documentation to use it

### ISSUE THREAD

**Issue by aukgit** [adamhathcock/sharpcompress#292]
There is no proper documentation to use it

Please add proper documentation and example to compress and uncompress with 7Zip LZMA with other parameters like with encryption, with a password and so on. 

This source is not usable at all.

**Comment by adamhathcock** [comment]
I’m sorry you feel that way.  Feel free to submit documentation and help or use another library.

**Comment by aukgit** [comment]
Thank you @adamhathcock for getting back to me. 
I have checked https://github.com/adamhathcock/sharpcompress/blob/master/USAGE.md

Will you please update a bit and add some examples of using password and multiple threads like 7zip GUID options

![image](https://user-images.githubusercontent.com/4561204/30002170-5a1581e4-90c4-11e7-988c-9ebb7d1b6ef7.png)

**Comment by aukgit** [comment]
I had tried with 7zip, from 7zip GUI it takes 8 seconds but from this library and below code it takes more than 4 mins.
![image](https://user-images.githubusercontent.com/4561204/30002187-b72a289e-90c4-11e7-9c00-c9c73bf7fb11.png)

7Zip with Ultra 1 GB file became 18MB
with this library, the 7zip method converts to 22 MB
![image](https://user-images.githubusercontent.com/4561204/30002194-f3980ff8-90c4-11e7-837f-38ad4ba4b746.png)

**Comment by adamhathcock** [comment]
FYI, you made a zip file not a 7Zip file.  The documentation clearly says it doesn’t support creating 7Zip files: https://github.com/adamhathcock/sharpcompress/blob/master/FORMATS.md

There isn’t multi-threading support built in and not all of LZMA’s options are exposed nicely like in the 7Zip GUI.

7Zip support is pretty raw as the format itself is rather ugly.  I recommend using another format like LZip anyway.

I have no plans to make 7Zip support better but the options are there if you want to add code for what you need.  Pull Requests are welcome.

**Comment by aukgit** [comment]
@adamhathcock Thank you again.

I was checking that doc too but the problem is it is not supporting LZMA2, I can only use LZMA. 

For multi thread will you please give me some idea where I can modify a bit to use multithread up to 167 threads.

**Comment by aukgit** [comment]
Somehow lzip is failing 
![image](https://user-images.githubusercontent.com/4561204/30002333-8241e960-90c8-11e7-8c31-2adddebd5c77.png)

**Comment by adamhathcock** [comment]
You’re still trying to make zip files.  LZMA vs LZMA2 isn’t your problem.

You need to dig into the code and understand the difference between Zip and 7Zip as archive formats vs compression methods.
