### ISSUE TITLE
Double Dispose() of ZipWritingStream

### ISSUE THREAD

**Issue by aienabled** [adamhathcock/sharpcompress#294]
Hello!

I've noticed that ZipWritingStream on `Dispose` method call will produce a new ZipEntry.
But it doesn't have protection against subsequent `Dispose` call. For example:
```C#
using (var stream = zipWriter.WriteToStream(FileNameHeader, new ZipWriterEntryOptions()))
using (var streamWriter = new StreamWriter(stream))
{
   ...
}
```
it will call dispose for ZipWritingStream two times and produce two zip entries in the archive.
I didn't checked it for other streams (non-zip) but they also could be affected by this issue.

Regards!

**Comment by adamhathcock** [comment]
Good find.  Any chance for a pull request? :)

**Comment by aienabled** [comment]
Sure https://github.com/adamhathcock/sharpcompress/pull/295

**Comment by adamhathcock** [comment]
Thanks!
