### ISSUE TITLE
"Memory stream is not expandable" exception

### ISSUE THREAD

**Issue by KvanTTT** [adamhathcock/sharpcompress#306]
I'm trying to extract [MemoryStreamIsNotExpandable.zip](https://github.com/adamhathcock/sharpcompress/files/1369909/MemoryStreamIsNotExpandable.zip) with the following code:

```CSharp
using (Stream stream = File.OpenRead(sourceArchiveFileName))
{
    using (IReader reader = ReaderFactory.Open(stream))
    {  
        while (reader.MoveToNextEntry())
        {
           ...
        }
    }
}
```

But got "Memory stream is not expandable" exception after reading of big.png file at `while (reader.MoveToNextEntry())` line. This file received from standard Mac compress utility.

With the reason of this error and how can we resolve it?

**Comment by adamhathcock** [comment]
Looks like that's a streaming zip and the rewindable buffer can't handle a MemoryStream with a given buffer.  Not sure why I hadn't seen this until now.  Made a PR

**Comment by anuprajg** [comment]
Is there a plan to Merge this pull request and release a new build?
