### ISSUE TITLE
rar5 archive type from RAR5 branch give me error

### ISSUE THREAD

**Issue by sorset** [adamhathcock/sharpcompress#311]
if (CurrentSignatureType == SignatureType.Rar5)
            {
                throw new ArchiveException("Unknown Rar5 is supported");
            }

The problem is that I can not check Signature property outside of library.
Need to implement public property to check .

For example:

if (reader.Signature == Rar5)
 return;
else
 //   do something with my archive in my solution...

**Comment by adamhathcock** [comment]
RAR5 supported as of https://github.com/adamhathcock/sharpcompress/pull/340 no rar5 decryption though
