### ISSUE TITLE
The extract files` modified time are wrong.

### ISSUE THREAD

**Issue by WcLyic** [adamhathcock/sharpcompress#314]
Version:0.18.2
Archive:TestArchives\Archives\Zip.deflate.zip

Below is the code i used. The extract files` modifiled time just like the create time rather than the modifiled time of original file.
```csharp
using (archive = ArchiveFactory.Open(path,
    new ReaderOptions { ArchiveEncoding = new SharpCompress.Common.ArchiveEncoding { Default = Encoding.Default } }))
{
    archive.WriteToDirectory(expath,
        new ExtractionOptions
       {
            ExtractFullPath = true,
            Overwrite = true
       });
 }
```

**Comment by adamhathcock** [comment]
Sorry, I think you'll have to be more specific.

The modified time of the extracted file matches the create time instead of using the last modified time from the zip?

**Comment by WcLyic** [comment]
Version:0.21.1
Sample:[Link](https://mega.nz/#!UwslzaCD!TR24QtW_B6p4W9Jz1ufQB0WCBZL6Ntj4e3BUtp354vY)

Sorry for reply after long time. Here is the sample of what I want to point out.

In archive:
![image](https://user-images.githubusercontent.com/29097441/40265832-6e2fbc0c-5b72-11e8-902e-8a027edf2946.png)
After extracted:
![image](https://user-images.githubusercontent.com/29097441/40265837-83614a28-5b72-11e8-8bf3-debe65519647.png)

**Comment by WcLyic** [comment]
Finally I found the option "PreserveFileTime", it solved my question.
