### ISSUE TITLE
Q: ArchiveType vs CompressionType

### ISSUE THREAD

**Issue by evil-shrike** [adamhathcock/sharpcompress#316]
Hi!

I can't understand how to choose a format. When I create a stream I use `ArchiveFactory.Create(ArchiveType.Zip)` but then I have to choose CompressionType : 
```
_zipStream = ArchiveFactory.Create(ArchiveType.Zip);
_zipStream.SaveTo(PackageStream, new WriterOptions(CompressionType.GZip));
```
why? How do ArchiveType and CompressionType relate to each other?

Moreover this code throws SharpCompress.Common.InvalidFormatException: Invalid compression method: GZip.
Zip archive can't have GZip compression type? 
I found out that ArchiveType.Zip is compatible with CompressionType.Deflate. But it's weird API.

**Comment by adamhathcock** [comment]
You've got it it seems.  Yes, GZip is slightly weird and isn't supported on Zip as detailed here: https://github.com/adamhathcock/sharpcompress/wiki/Supported-Formats

Yes, it is slightly weird because it's trying to be powerful.  If you've got suggestions on how to fix the API, then please let me know.

**Comment by evil-shrike** [comment]
Ok, got it.
ArchiveType determines a subset of compression types.
Well, I'd suggest some default `SaveTo`:
```
interface IWritableArchive {
  void SaveTo(Stream stream, WriterOptions options = null);
}
```
if no `WriterOptions` was specified then the lib will choose some default based on its ArchiveType.

**Comment by adamhathcock** [comment]
You can also just put `CompressionType` in directly as it's implicitly converted.

**Comment by evil-shrike** [comment]
Ok, that's nice. 
But I meant to allow skipping `CompressionType` at all: `zipArchive.SaveTo(stream)`

**Comment by adamhathcock** [comment]
Yeah that's fine too.

**Comment by evil-shrike** [comment]
but it doesn't work ) there's no such method in `IWritableArchive`

**Comment by adamhathcock** [comment]
Looks like this https://github.com/adamhathcock/sharpcompress/blob/master/tests/SharpCompress.Test/Zip/ZipArchiveTests.cs#L269
