### ISSUE TITLE
.Net Core compatibility ?

### ISSUE THREAD

**Issue by Zeugma440** [adamhathcock/sharpcompress#318]
Hey there,

On the main page, you mention that sharpcompress is for ".NET 3.5, 4.5, .NET Standard 1.0, 1.3"

However, there is no mention of .NET Core compatibility. Could you check which version does it work with ?

Best regards,

-Z440

**Comment by adamhathcock** [comment]
.NET Core implements the .NET Standard 1.0 and higher.  It will work.

**Comment by Zeugma440** [comment]
Oh. Right. Thanks for the quick answer !
