### ISSUE TITLE
Runtime problems after updating from v0.18.2 to v0.19.0

### ISSUE THREAD

**Issue by michalkrzych** [adamhathcock/sharpcompress#330]
If you're still using .NET 4.6.1 don't upgrade to SharpCompress version 0.19.0 as it seems to be using System.Buffers which depends on .NET Standard 2.0 libraries (System.Net.Http 4.2.0.0 and System.ValueTuple 0.0.0.0) causing a mismatch between the version of .dlls as .NET 4.6.1 is still using System.Net.Http 4.0.0.0 and System.ValueTuple 4.4.0 (from NuGet). 

So I think the backward compatibility of SharpCompress is broken for anyone who doesn't use .Net Standard yet...

**Comment by tobiasschulz** [comment]
Version 0.19.0 broke my Xamarin app completely. The problem is that System.Buffers.dll is not available on Mono and Xamarin.Android/iOS. This version is completely useless and no longer cross platform.

**Comment by tobiasschulz** [comment]
System.Buffers should only be referenced in a .net framework and .net core specific dll. The .net standard version can't reference it.

**Comment by adamhathcock** [comment]
.NET 4.6.1 should be using the .NET Standard 2.0...I'm not sure about the issue there.  

As for Mono/Xamarin...I guess it's using the .NET 4.5 version instead of the .NET Standard 1.0 version?

**Comment by adamhathcock** [comment]
Cross targetting is a nightmare.  I should just absorb the arraypool classes in or remove the pooling.

**Comment by tobiasschulz** [comment]
No it's using the .net standard version, but that version depends on System.Buffers which is not cross platform.

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/sharpcompress/0.19.1
