### ISSUE TITLE
Please do not absorb System.Buffers. Thanks

### ISSUE THREAD

**Issue by yinyue200** [adamhathcock/sharpcompress#332]
Just use a lower version (4.0) can make ArrayPool running on Mono. Absorbing System.Buffers broke some app that already referenced System.Buffers. because your make a `public abstract class ArrayPool<T>`
Absorbing System.Buffers make the library can't use the shared object of ArrayPool, it reduce the benefits.
Thanks.

**Comment by yinyue200** [comment]
Sample repo
![tim 20171216093502](https://user-images.githubusercontent.com/13848771/34066069-761d05ac-e244-11e7-81f7-88235c6e8662.png)

**Comment by adamhathcock** [comment]
Yeah I should have changed the visibility and probably even namespace.  Will fix and release

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/sharpcompress/0.19.2
