### ISSUE TITLE
Question : Find number of entries in the commpressed file

### ISSUE THREAD

**Issue by trDiablo** [adamhathcock/sharpcompress#355]
Hello,

Is it possible to know the number of entry in a Zip file without reading and count all entrie ?

Currently i use 
```
int nb = 0;
while (reader.MoveToNextEntry())
{
   if (!reader.Entry.IsDirectory) nb++;
}

```
but i have a performance issue about 3 or 4 second to a Zip file of 98Mb with 52 entries in it.
I probably missed a documentation but I did not find how to do.

Thx for your help

**Comment by xupefei** [comment]
Use `ArchiveFactory` whenever possible. It a lot faster than `ReaderFactory`.

**Comment by trDiablo** [comment]
Thx i have now the entry easily :) 

For perfomances issues, i have same time with ReaderFactory or ArchiveFactory, decoding the whole file take 5 or 6 secondes (98 Mo, for 52 jpg entry).

I check my code to find if, and how, I can defer loading.

Thx
