### ISSUE TITLE
RAR5 Uncompression Unsupported 

### ISSUE THREAD

**Issue by kuaile2818** [adamhathcock/sharpcompress#356]
RAR5 Uncompression Unsupported 
DLL Version:v0.19.2

[Unsupported File [RAR5.0].zip](https://github.com/adamhathcock/sharpcompress/files/1787417/Unsupported.File.RAR5.0.zip)

**Comment by adamhathcock** [comment]
This is known

**Comment by adamhathcock** [comment]
RAR5 supported as of https://github.com/adamhathcock/sharpcompress/pull/340 no rar5 decryption though
