### ISSUE TITLE
ZipArchive Reader: File name and comments should not be decoded using UTF8 if the general purpose bit 11 is not set in the header

### ISSUE THREAD

**Issue by sridhar6668** [adamhathcock/sharpcompress#362]
As per the zip format specification, If general purpose bit 11 is unset, the file name and comment should conform to the original ZIP character encoding(IBM PC character encoding set). Currently, the code always uses the UTF8 to decode the name and comment and it results in garbled strings if the name was encoded using IBM PC character encoding set.

**Comment by adamhathcock** [comment]
https://github.com/adamhathcock/sharpcompress/pull/363 fixes this
