### ISSUE TITLE
Projects in solution fail to load

### ISSUE THREAD

**Issue by StrikerMan780** [adamhathcock/sharpcompress#364]
All the projects in the solution for SharpCompress fail to load in VS2017. Don't have any more detail since VS isn't giving me any. It just says "One or more projects in the solution were not loaded correctly."

**Comment by adamhathcock** [comment]
i'm not sure what to tell you.  I'm pretty sure it works for others and me the last time I tried it.  I'm usually on a mac using the command line or Rider.

**Comment by Headkillah** [comment]
I can guarantee you that all solutions works like a charm in VS 2017.

**Comment by StrikerMan780** [comment]
Well, they don't work like a charm, sorry to say. They simply will not load.

This is on Windows, not any other platform.

**Comment by adamhathcock** [comment]
Having used it with VS2017 in the past and someone else confirming it works, I'm going to assume this is environmental.  I recommend trying another .NET Standard/.NET Core project and checking your installation options.
