### ISSUE TITLE
leaveOpen argument for XZStream constructor

### ISSUE THREAD

**Issue by ied206** [adamhathcock/sharpcompress#368]
While `SharpCompress.Compressors` classes like `DeflateStream` and `BZip2Stream` have `leaveOpen` argument in its constructor, `XZStream` and `RarStream` does not.

Is there any special reason for this? It would be better to have `leaveOpen` to every Stream in `SharpCompress.Compressors`, to match convention of `System.IO.Compression`.

**Comment by adamhathcock** [comment]
No special reason other than just didn’t think about it.

Rather than implementing `leaveOpen` on each, I should remove it and use `NonDisposingStream` to wrap instead.

**Comment by adamhathcock** [comment]
Fixing here: https://github.com/adamhathcock/sharpcompress/pull/369

**Comment by ied206** [comment]
Thanks for fixing!
