### ISSUE TITLE
EntryStream.Length should delegate to the underlying stream

### ISSUE THREAD

**Issue by coderb** [adamhathcock/sharpcompress#370]
adam-

Could you please make the change below?  

I have a use case where I want to check the uncompressed stream size.

thanks,
b

EntryStream.cs:
from:
        public override long Length
        {
            get { throw new NotSupportedException(); }
        }

to:
 public override long Length
        {
            get { return stream.Length; }
        }

**Comment by adamhathcock** [comment]
Are you sure that would work?  Usually the streams don't know their length because they're compressed.  I guess certain use-cases it would work.

**Comment by coderb** [comment]
It works for RARs as the header contains the uncomrpessed size and hopefully for others that don't know will continue to throw NotSupportedException.
