### ISSUE TITLE
Can't use custom decoder or default encoding for ZIP without UTF8 supporting

### ISSUE THREAD

**Issue by saragulov** [adamhathcock/sharpcompress#380]
After fix https://github.com/adamhathcock/sharpcompress/pull/363 it became impossible to use custom decoder or default encoding for ZIP with null bit 11. However, archives created by Windows 10 tools do not use the IBM 437 encoding. It looks like they use the current user encoding. Previously, you could specify it as the default encoding and the names were decoded successfully. But now it doesn't work.

**Comment by saragulov** [comment]
[Example.zip](https://github.com/adamhathcock/sharpcompress/files/2001325/Example.zip)
See this example zip archive.

**Comment by adamhathcock** [comment]
You're right....I will fix this now.

**Comment by adamhathcock** [comment]
@saragulov look at the PR and see if this works for you...I can merge and do a bugfix release if so.  I believe using Forced to override seems correct.

**Comment by saragulov** [comment]
Thank you for fix again. Can you do a bugfix release?

**Comment by saragulov** [comment]
Thank you very much! Been waiting for the RAR5 support
