### ISSUE TITLE
Zip Slip Vulnerability Fix

### ISSUE THREAD

**Issue by SeanGephardt1** [adamhathcock/sharpcompress#393]
Is there a fix for the Zip Slip Vulnerability?
When there is, what would be the best way to apply it to affected machines?

https://github.com/snyk/zip-slip-vulnerability

**Comment by adamhathcock** [comment]
As your link points out, it was fixed in 0.21 in this contributed pull request: https://github.com/adamhathcock/sharpcompress/pull/374

**Comment by SeanGephardt1** [comment]
It appears that several products are using outdated versions of the DLL. Sorry for the confusion.
