### ISSUE TITLE
Zip Slip Vulnerability Fix is not present in advertised nuget v 0.21.1

### ISSUE THREAD

**Issue by diaconesq** [adamhathcock/sharpcompress#394]
The Zip Slip vuln is fixed by #374 and should be included in v 0.21.0 as described [here](https://github.com/snyk/zip-slip-vulnerability)

However: I have decompiled versions 0.21.0 and 0.21.1 from Nuget.org (the .net 4.5 dll) and the fix is NOT there.

Decompiled Nuget code:
![image](https://user-images.githubusercontent.com/3482077/42028109-4af9f7aa-7ac3-11e8-98c1-eb96f64a6a3d.png)

The PR for the fix:
![image](https://user-images.githubusercontent.com/3482077/42028306-cab37ae8-7ac3-11e8-986d-d09706c35448.png)

**Comment by adamhathcock** [comment]
You'll notice the classes you're referencing are two different classes.

The issue isn't that it's missing but incomplete.  The implementation previously provided was for the Archive API and not the Reader API as you want.  This should be fixed.
