### ISSUE TITLE
Encoding 437 Data Could Not Be Found

### ISSUE THREAD

**Issue by ooikengsiang** [adamhathcock/sharpcompress#405]
The latest v0.22.0 version in Nuget caused some problem when trying uncompress 7z file in Xamarin Android and iOS. It show exception: Encoding 437 Data Could Not Be Found
Reverting back to v0.21.1 solved the problem.

**Comment by adamhathcock** [comment]
Also, give the full stack trace?  I just want to make sure why this is happening.

**Comment by adamhathcock** [comment]
Also, Encoding 437 has to do with Zip files, not 7Zip files.

**Comment by adamhathcock** [comment]
Probably the PR that changed this which was the netstandard1.0 build flag change: https://github.com/adamhathcock/sharpcompress/pull/385/files

**Comment by ooikengsiang** [comment]
I direct target on Android / iOS project. I have attached a sample Android project here.
Note: It only happen on release mode, debug mode have no problem.
[UncompressApp.zip](https://github.com/adamhathcock/sharpcompress/files/2216047/UncompressApp.zip)

**Comment by adamhathcock** [comment]
Give me the stacktrace for your project, please.  I’m not going to set up the tooling to run it.

**Comment by ooikengsiang** [comment]
Since I can't easy copy paste the stack trace on release mode, here are the screenshot of the stack trace, hope it can help.
![sharpcompressencodingerror](https://user-images.githubusercontent.com/19687809/43034578-85c5e014-8d11-11e8-92a2-467f28010d95.PNG)

**Comment by adamhathcock** [comment]
Thanks, that’s perfect

**Comment by gblikas** [comment]
I am not sure if this is the correct fix, but I was seeing the same problem while trying to use `Ionic.Zip.dll`. My solution was to copy the `I18N.*.dll`'s into the `Assets` folder. This solved it for Android and iOS. For some reason, it seems like Unity doesn't include some essential code page support in its Mobile build pipeline.

**Comment by adamhathcock** [comment]
Hopefully, that's a solution.  This type of thing being cross-platform is horrendous to debug and fix.

**Comment by gblikas** [comment]
@adamhathcock It always is, and especially with some many Android API levels, it can make it even worse! 

Also, sorry if my quick fix doesn't work. I have just started using Unity.

**Comment by ooikengsiang** [comment]
@gblikas Thanks for your suggestion, but my app did not use Unity. This problem can trigger through a simple Android app like the sample provided.
I haven't got the chance try the latest version of the library see if the problem still exist or not.

**Comment by ooikengsiang** [comment]
I tested the newest version, but now I force it to use UTF8 encoding instead which was the default encoding in v0.21.1
```
var readerOptions = new ReaderOptions();
readerOptions.ArchiveEncoding.Default = System.Text.Encoding.UTF8;
```

**Comment by Adit2705** [comment]
I had the same problem and has been driving me crazy. This affected both iOS and Android for me.

Under the Android project settings: Android Options -> Linker -> Check all Additional supported encodings.
iOS: Project Options -> iOS Build -> Advanced tab -> Internationalization -> Check all options.

**Comment by JamestsaiTW** [comment]
When I upgrade to nuget v0.25.0 of SharpCompress, this issue was be fixed. Try it.

**Comment by gblikas** [comment]
@JamestsaiTW Do you know what changed between that and previous version fix it, if it is indeed fixed?

**Comment by adamhathcock** [comment]
I changed some of the targets which may have had an effect.  Still no idea what would cause or fix the issue for iOS

**Comment by JamestsaiTW** [comment]
I guess the "System.Text.Encoding.CodePages" library was changed from 4.5.0 to 4.7.0.

**Comment by ooikengsiang** [comment]
Just tried version 0.25.0 on Android, still have the same exception :(

**Comment by adamhathcock** [comment]
Having finally my own use case (Blazor WASM) I see that eager loading the encoding is an issue.  Need to refactor to set different encodings.

Need to also remember why 437 was the default.  I think it was zip spec.

**Comment by adamhathcock** [comment]
New release https://www.nuget.org/packages/sharpcompress/0.26.0 should fix this
