### ISSUE TITLE
Wrong unpacking zip archive with stored another ones

### ISSUE THREAD

**Issue by Yet371** [adamhathcock/sharpcompress#406]
There is an example of archive:
[1.zip](https://github.com/adamhathcock/sharpcompress/files/2213855/1.zip)

the archive contains these files:
   11 1.txt
  472 internal1.zip
  472 internal2.zip

but reader.MoveToNextEntry() sees this:
11 1.txt
 0 internal1.zip
10 internal11.txt
10 internal12.txt
10 internal13.txt

**Comment by adamhathcock** [comment]
Probably same as https://github.com/adamhathcock/sharpcompress/issues/86

**Comment by Yet371** [comment]
Yes. Seems like that. Sorry for the duplication
