### ISSUE TITLE
Tar filename with exactly 100 characters gets cut

### ISSUE THREAD

**Issue by majoreffort** [adamhathcock/sharpcompress#407]
Filenames with exactly 100 characters loose their last character while writing the header (TarHeader#Write).

I wrote a simple test to verify this issue: See ec044e6f42a60159e36b95689960ba55e4fbcb4f

I also digged into the code and found the method `WriteStringBytes` actually writes a maximum of length-1 bytes:
```csharp
for (i = 0; i < length - 1 && i < name.Length; ++i)
{
    buffer[offset + i] = (byte)name[i];
}
```
Is this intended and/or tar only supports 99 character entries?
If I replace `length - 1` with only `length` the tar tests work fine.

**Comment by adamhathcock** [comment]
Mind submitting the test and a fix as a pull request?  Thanks!

**Comment by majoreffort** [comment]
Sure, added PR #408.
