### ISSUE TITLE
In-place support for ordinary directories?

### ISSUE THREAD

**Issue by cmpute** [adamhathcock/sharpcompress#420]
I found it useful if the normal directory can be added as an archive type so that I don't have to maintain two copies of code when dealing with either archived files or unarchived files. Do you have plan to or do you accept to add ordinary directories as an archive type so that unified access is obtained? I can offer some help on this.

**Comment by adamhathcock** [comment]
I will accept PRs around this problem if you've got time :)

I originally didn't do it because I thought empty directories didn't make sense.  I'm not 100% sure all formats allow it but it's something that ought to be done after looking back after 10-15 years of this project.

**Comment by cmpute** [comment]
I found that the library is currently designed for file archives, which directories are actually not. So I think this propose may be not feasible. Thus I decide to close it.
