### ISSUE TITLE
System.DivideByZeroException

### ISSUE THREAD

**Issue by antimYT** [adamhathcock/sharpcompress#445]
i get System.DivideByZeroException when i try to compress empty txt file.
[screenshot](https://imgur.com/a/VCamdGH)
ArchiveType = Zip
CompressType = BZip2

**Comment by antimYT** [comment]
File: SharpCompress\Compressors\BZip2\CBZip2OutputStream.cs
Error line: 1344

**Comment by adamhathcock** [comment]
My first thought is "don't do that." but I guess zip allows for empty files?

You could just set to no compression on that entry.
