### ISSUE TITLE
Since version 0.19 iOS zip open stream doesn't work

### ISSUE THREAD

**Issue by ivanicin** [adamhathcock/sharpcompress#446]
The exception is raised on this line:

`using (var archive = SharpCompress.Archives.Zip.ZipArchive.Open(fileStream))`

The strange thing is that if I catch the exception it is null, so I can't provide any other info...

The same code works on UWP in all versions of SharpCompress, but on iOS 0.18.2 is the last version that processes this line properly.

**Comment by adamhathcock** [comment]
Can only guess it has something to do with .NET Standard 2.0 targetting.  I don't use iOS (Xamarin?) so will need help.

here's the changelog for 0.19: https://github.com/adamhathcock/sharpcompress/releases/tag/0.19

**Comment by ivanicin** [comment]
It works on Xamarin.Android, so it is isolated to Xamarin.iOS and I think Xamarin.Mac.

Surely I can help if it means that I should test some code report exceptions etc.

**Comment by ivanicin** [comment]
I found the bug it is here:

```
        public ArchiveEncoding()
        {
            Default = Encoding.GetEncoding(437);
            Password = Encoding.GetEncoding(437);
        }
```
This is causing System.NotSupportedException on iOS and macOS

Using any other encoding like UTF8 resolves this for me.

@adamhathcock can you fix the problem with this info?

**Comment by ivanicin** [comment]
Also this means that this can work on iOS if you check 'west' in internationalization project properties, but it is unchecked by default.

**Comment by adamhathcock** [comment]
I should probably just change it to be Encoding.Default because 437 is problematic and old.  I think it was just the default for Zip files back in the day.

**Comment by adamhathcock** [comment]
New release https://www.nuget.org/packages/sharpcompress/0.26.0 should fix this
