### ISSUE TITLE
Does this support password-protected-archive unpacking (RAR/ZIP/TAR...) (mostly for RAR format)?

### ISSUE THREAD

**Issue by NadirTennci** [adamhathcock/sharpcompress#451]
I can't find the password argument in the RARArchive's open function

**Comment by adamhathcock** [comment]
https://github.com/adamhathcock/sharpcompress/blob/master/tests/SharpCompress.Test/Rar/RarArchiveTests.cs#L52

**Comment by tardezyx** [comment]
@adamhathcock
Your test code does not work. I've tried to decompress it with ArchiveFactory.Open and RarArchive.Open - with stream and with direct path. Neither worked.

Code is:

```
ReaderOptions ro = new ReaderOptions();
ro.Password = password;
ro.LeaveStreamOpen = true;

Stream stream = File.Open(path, FileMode.Open);
IArchive archive = RarArchive.Open(stream, ro);

foreach (IArchiveEntry entry in archive.Entries.Where(entry => !entry.IsDirectory))
{
	entry.WriteToDirectory(Helper.GetRegValue("\\Paths", "ExtUP"), new ExtractionOptions() { ExtractFullPath = true, Overwrite = true });
}
archive.Dispose();
```

**Comment by adamhathcock** [comment]
Funny because the tests run and pass.

RAR5 decryption is a TODO item.
