### ISSUE TITLE
Handle bad extra fields in local file headers in zip files

### ISSUE THREAD

**Issue by DannyBoyk** [adamhathcock/sharpcompress#454]
At my work we have to process quite a few zip files whose generation we have very little control over.  One of the zips we are receiving is putting custom data in the extras field of the local file header rather than following the 2 byte tag ID, 2 byte value length, and X byte value that the zip format specifies.

I traced 7zips logic on this and they just gracefully bail on further parsing of the extras field if they detect a length for an extra that is greater than the total length of the extras header.  I made a similar change in ZipFileEntry and added a corresponding test.  I'll be pushing up a branch and making a PR for this issue.

**Comment by adamhathcock** [comment]
Seemed fine to me.  Thanks.
