### ISSUE TITLE
Excel files corrupted after extraction in password protected RAR file

### ISSUE THREAD

**Issue by Mohammadhamza43** [adamhathcock/sharpcompress#479]
I want to extract the password protected .rar file but when i extracted the .rar file the folder containing the excel file extracted but all the files in there are corrupted. It works fine when i extract non-password protected file.

Directory Structure:
example.rar --> example --> book1.xlsx

This is what i m doing:
using (var archive = RarArchive.Open(@"C:\Users\User\Desktop\example.rar", new SharpCompress.Readers.ReaderOptions() {
                Password = "12345678"
            }))
            {
                foreach (var entry in archive.Entries.Where(entry => !entry.IsDirectory))
                {
                    entry.WriteToDirectory("D:\\temp1", new ExtractionOptions()
                    {
                        ExtractFullPath = true,
                        Overwrite = true,
                    });
                }
            }

**Comment by adamhathcock** [comment]
Probably is the wrong password.  The only way to detect wrong passwords is with CRC if I recall correctly.

**Comment by Mohammadhamza43** [comment]
extracting a file with wrong password is possible?

**Comment by adamhathcock** [comment]
What are you saying?  WinRAR itself will extract the file with the correct password?

Incorrect password will extract garbage as there’s no way to detect if the password is correct without doing a CRC of the file.

**Comment by Mohammadhamza43** [comment]
what i m saying is that when i extract the same file manually using winrar with the same password it works fine. but with the above code its giving me garbage

**Comment by adamhathcock** [comment]
I'm not sure what to tell you unless you can speak more of the encryption options and how they're different from the tests in the repo
