### ISSUE TITLE
Can't decompress some .RAR files

### ISSUE THREAD

**Issue by IvanSorokin** [adamhathcock/sharpcompress#490]
Hello, I am getting exception 

```
SharpCompress.Common.InvalidFormatException: Invalid Rar Header: 251 at SharpCompress.Common.Rar.Headers.RarHeaderFactory.ReadNextHeader(Stream stream)
```

SharpCompress: 0.24  
[examples.zip](https://github.com/adamhathcock/sharpcompress/files/3778746/examples.zip) contains two rar files. Can extract them using 7zip or WinRar (5.71)  but no luck with SharpCompress =(

Maybe these are RAR 5 archives which are not supported at the moment (it is stated in TODOS list on a main page)

**Comment by adamhathcock** [comment]
RAR5s are supported.  Decryption for RAR5 may not work.

**Comment by Nanook** [comment]
I'm closing this as the archives extract perfectly in the current version. Filenames and data match originals 1:1.
