### ISSUE TITLE
AddAllFromDirectory does not ignore files locked by other process

### ISSUE THREAD

**Issue by CaledoniaProject** [adamhathcock/sharpcompress#501]
I'm using the following code to compress a directory:

            using (var archive = ZipArchive.Create())
            {
                archive.AddAllFromDirectory(dirname);
                archive.SaveTo(zipname, options);
            }

When one of the files is not readable, it throws exception.

How can I let it continue and ignore files that can't be read?

**Comment by turbolocust** [comment]
Use the **AddEntry** method instead.
Take a look at the actual implementation:

```csharp
public static void AddAllFromDirectory(
	this IWritableArchive writableArchive,
	string filePath, string searchPattern = "*.*", SearchOption searchOption = SearchOption.AllDirectories)
{
	foreach (var path in Directory.EnumerateFiles(filePath, searchPattern, searchOption))
	{
		var fileInfo = new FileInfo(path);
		writableArchive.AddEntry(path.Substring(filePath.Length), fileInfo.OpenRead(), true, fileInfo.Length,
								 fileInfo.LastWriteTime);
	}
}
```
