### ISSUE TITLE
Error with net472 and v0.25

### ISSUE THREAD

**Issue by zplan** [adamhathcock/sharpcompress#511]
I have a net472 wpf application which references my own netstandard2.0 library. This library uses sharpcompress.

After updating sharpcompress to 0.25 in my library, the application is crashing.
Was this the intention of v0.25 that there is no support anymore for net472 framwork?

Error trace:
Pre-bind state information:
LOG: DisplayName = System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/MyProject/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : SharpCompress, Version=0.25.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96.
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\MyProject\bin\Debug\MyProject.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/MyProject/bin/Debug/System.Text.Encoding.CodePages.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/SharpCompress/

Nuget clearly spells out what is supported and what the dependencies are.  If your app is missing a file then I don’t know what to tell you.

**Comment by zplan** [comment]
Thanks for your fast response.
I forget to mention that System.Text.Encoding.CodePages.DLL is in the debug folder, but all versions I tried (4.7.1/4.7.0/4.6.1/4.5.0/...) --> error still occurs

**Comment by adamhathcock** [comment]
Seems like it's been built wrongly unless it's something silly like full framework is trying to use the netstandard20 reference when it should be using the net46 one.

Unfortunately, I don't have windows so I wont be able to help.  

0.24 works fine for you?

**Comment by zplan** [comment]
> 0.24 works fine for you?
Yes. error occured when I updated from 0.24 to 0.25

**Comment by adamhathcock** [comment]
I think I need to exclude the CodePages DLL just like in 0.24: https://github.com/adamhathcock/sharpcompress/pull/512

**Comment by adamhathcock** [comment]
Released in https://www.nuget.org/packages/sharpcompress/0.25.1

**Comment by zplan** [comment]
> Released in https://www.nuget.org/packages/sharpcompress/0.25.1

Thanks! --> It is working again.
