### ISSUE TITLE
SevenZipEntries.IsEncrypted is always set to False

### ISSUE THREAD

**Issue by evpxregu** [adamhathcock/sharpcompress#521]
When opening a sevenziparchive and checking the entries in the archive for all the entries IsEncrypted will be set to false.

You can see in the sourcode that the value is hardcoded.

https://github.com/adamhathcock/sharpcompress/blob/00ff119ec4f13020fb40bba3654d53e9836ebd6d/src/SharpCompress/Common/SevenZip/SevenZipEntry.cs

**Comment by Sicos1977** [comment]
I have the same problem and made issue #539 for it
