### ISSUE TITLE
Please update description to include lz (LZMA) write support

### ISSUE THREAD

**Issue by MrM40** [adamhathcock/sharpcompress#525]
It's not mentioned on the Nuget repository page nor in the introduction section here on Github.
In my view it's one of the most important features and it not worthy of only being mentioned as a site-note somewhere ;-)

**Comment by adamhathcock** [comment]
I'll take a PR for whatever you want written in :)

Just busy with work and a new baby so little headspace even for simple things.

**Comment by MrM40** [comment]
Uhh....then you sure are busy, congratulation :-)
You write "Write support for zip/tar/bzip2/gzip are implemented." Just add "LZ(lzma)" to that sentence.
I've been skipping this project several time because I though it didn't had LZMA write support, but it turns out you implemented it long time ago, and that's really nice, just "spread the word":-)

**Comment by adamhathcock** [comment]
Ill try to remember to do it when I'm back at a computer.

Actually, Jon Skeet implemented LZip read and write for Nodatime and I got LZMA/7Zip basics from contributors as well.

Always looking for someone to help maintain though since recent years I haven't had the time!

**Comment by adamhathcock** [comment]
Just needed to update the readme.  I think the Nuget description was right
