### ISSUE TITLE
entry.IsEncrypted is false when a 7z file has an AesDecoderStream

### ISSUE THREAD

**Issue by Sicos1977** [adamhathcock/sharpcompress#539]
Is it somehow possible to set the IsEncrypted to true when the 7z file has an AesDecoderStream?

I use the IsEncrypted flag to check is a file is password protected so in this case I would expect it to be true

        internal static Stream CreateDecoderStream(CMethodId id, Stream[] inStreams, byte[] info, IPasswordProvider pass,
                                                   long limit)
        {
            switch (id._id)
            {
                case K_COPY:
                    if (info != null)
                    {
                        throw new NotSupportedException();
                    }
                    return inStreams.Single();
                case K_LZMA:
                case K_LZMA2:
                    return new LzmaStream(info, inStreams.Single(), -1, limit);
                case CMethodId.K_AES_ID:
                    return new AesDecoderStream(inStreams.Single(), info, pass, limit);
                case K_BCJ:

**Comment by Sicos1977** [comment]
Any updates on this?

**Comment by Sicos1977** [comment]
Any updates?

**Comment by adamhathcock** [comment]
Happy to accept pull requests

**Comment by Sicos1977** [comment]
If you can give me some ideas how to do this I would be happy to do it.
