### ISSUE TITLE
Make ArchiveFactory.Open case sensitive

### ISSUE THREAD

**Issue by AdamJurga** [adamhathcock/sharpcompress#554]
Hi Guys,

Is it possible to make ArchiveFactory.Open() case sensitive?

I'm reading some files from FTP server which is case sensitive and I can have two different files with "the same" name. 
TEST.zip and test.zip for example.

When I use ArchiveFactory.Open() always "test.zip" file is being picked, no matter what case I use (TEST.zip, test.zip, Test.zip, etc.).

Thanks,
Adam

**Comment by adamhathcock** [comment]
Case sensitivity is based on your file system (when using string or FileInfo overload) or your own code when using the Stream overload.

**Comment by AdamJurga** [comment]
It's case insensitive. This is why I'm asking 😊.
I would like to ArchiveFactory.Open() respect case sensitivity instead of using FindFirstFile. Is there a way?

**Comment by adamhathcock** [comment]
I'm saying my code isn't making a decision on that when using ArchiveFactory.Open.  It's based on filesystem and the base class library.

**Comment by AdamJurga** [comment]
Roger that, thank you sir!
