### ISSUE TITLE
Detect if 7zip file has data after payload

### ISSUE THREAD

**Issue by Louhike** [adamhathcock/sharpcompress#556]
I'm working on a tool (https://github.com/Louhike/Ugly-GDEmu-Games-Manager) where I want to analyze specific files in archives.

My problem is that when I use OpenEntryStream from an entry of a 7z file, it sometimes takes a lot of time.
It seems to happen specifically with archives with data after end of payload:
![image](https://user-images.githubusercontent.com/450826/102905401-5ef56380-4473-11eb-91d8-41ee7782fb56.png)

If I extract the content and create a new 7z file, OpenEntryStream isn't slow on its entries.

So I would like to bypass those files and warn the users. Can I do that with SharpCompress?

**Comment by Louhike** [comment]
I can provide you with a code example and a 7z file if required

**Comment by adamhathcock** [comment]
7zip is the most complex and my most disliked format.

If you dig into the format the code might do what you need.  You probably can't do it from the higher level interface.

I'm unlikely to have time to help in any detail so apologizes!

**Comment by Louhike** [comment]
That's ok, thanks for the help! I will take a look at it.
