### ISSUE TITLE
zip-archive and rar-archive have different folder separators

### ISSUE THREAD

**Issue by daniilzaonegin** [adamhathcock/sharpcompress#564]
Hi!
Is it alright, that library returns different folder separators for rar and zip?
For example

```c#   
class Program
    {
        static void Main(string[] args)
        {
            using (Stream stream = File.OpenRead("c:\\temp\\HeliosLogs.rar"))
            using (IArchive archive = ArchiveFactory.Open(stream))
            {
                foreach (IArchiveEntry entry in archive.Entries)
                {
                    Console.WriteLine($"EntryKey:{entry.Key}");
                }
            }

            using (Stream stream = File.OpenRead("c:\\temp\\HeliosLogs.zip"))
            using (IArchive archive = ArchiveFactory.Open(stream))
            {
                foreach (IArchiveEntry entry in archive.Entries)
                {
                    Console.WriteLine($"EntryKey:{entry.Key}");
                }
            }

        }
    }
```
This program returns

![image](https://user-images.githubusercontent.com/28781018/104738704-eb373580-5756-11eb-8f81-d125231e9641.png)

We have a solution, that opens archive and shows tree-structure to the user with folders and files. 
And I had to handle this case, because we split entry.Key either by "\\" or by "/" for building tree structure.
I think library should return unified folder separators independent of archive type.

**Comment by adamhathcock** [comment]
Entry.Key is a string that comes directly from the archive.  It's not interpreted as a file path.  The `Write` extension methods do this.  This library is not intended to be a high level API to do what you're asking.

**Comment by daniilzaonegin** [comment]
Okay, thank you! Then I will rewrite my code and I will extract files to folder and then tree-structure based on this folder.
