### ISSUE TITLE
tar file throwing "Rar signature not found"

### ISSUE THREAD

**Issue by PaulMcGuinness** [adamhathcock/sharpcompress#576]
I'm getting the following error on a .tar file 

SharpCompress.Common.InvalidFormatException: 'Rar signature not found'

When it's not a 'rar' file at all..... 

Is there an option to define the type instead of letting it decide itself?

**Comment by adamhathcock** [comment]
What are you using?

The Rar detection uses that exception then catches it currently so that's expected as an internal exception.

**Comment by PaulMcGuinness** [comment]
It's a TAR backup from a Cisco CUCM PABX.... Unfortunately I can't put it here as it contains customer data :-(

If I use an alternative library for this file, it works fine.

**Comment by adamhathcock** [comment]
I meant, what is the code?

You can use TarReader.Open or TarArchive.Open directly if you don't like the autodetection

**Comment by PaulMcGuinness** [comment]
```
public Stream GetFile(string path)
        {
            using var archiveStream = File.OpenRead(archivePath);
            using var archiveReader = ReaderFactory.Open(archiveStream);
            while (archiveReader.MoveToNextEntry())
            {
                if (!archiveReader.Entry.IsDirectory)
                {
                    var entry_name = archiveReader.Entry.ToString();
                    if (entry_name.EndsWith(path, StringComparison.OrdinalIgnoreCase) ||
                        entry_name.ToLower() == path.ToLower())
                    {
                        var temp = new MemoryStream();
                        archiveReader.OpenEntryStream().CopyTo(temp);
                        temp.Position = 0;
                        return temp;
                    }
                }
            }
            return null;
        }
```

**Comment by adamhathcock** [comment]
You can just change `ReaderFactory` to `TarReader` and it's fine.

Might want to be careful to dispose more stuff there.  You also double check you need to buffer in memory as you can just stream the contents of entries directly to whatever.

**Comment by PaulMcGuinness** [comment]
Many thanks
