### ISSUE TITLE
.NET4.6.2 Winform throw exception.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [adamhathcock/sharpcompress#588]
“PerTypeValues`1”的类型初始值设定项引发异常。

---InnerException：
未能加载文件或程序集“System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by SplitGemini** [comment]
.net 4.8 Same.
