### ISSUE TITLE
Zip64 Extra Header is not parsed conditionally

### ISSUE THREAD

**Issue by DannyBoyk** [adamhathcock/sharpcompress#595]
The current logic for the Zip64 extra header assumes that certain fields are present by the number of bytes in the extra header, but the specification indicates that the fields that are being parsed are based on the values in the local entry header, namely that the fields in the extra header correspond to those fields in the local header that are set to uint.MaxValue (or ushort.MaxValue for the disk number).

We have encountered Zip64 files in our production systems that only specify a compressed size in their Zip64 extra fields and SharpCompress assumes these represent the uncompressed size since only one value is specified.

**Comment by adamhathcock** [comment]
Released https://www.nuget.org/packages/SharpCompress/0.28.3
