### ISSUE TITLE
Chunked read for ZLibBaseStream might give error results

### ISSUE THREAD

**Issue by amosonn** [adamhathcock/sharpcompress#615]
When using `DeflateStream` (which wraps ZLibBaseStream), if the size of the read is unfortunate, we might not get all of the compressed data. When the read from the `DeflateStream` on which the last piece of input data is read is not large enough to read all of the deflated data, the rest will get lost, since we already set the "`nomoredata`" flag. See PR #616 for example test which fails and for fix.

**Comment by adamhathcock** [comment]
Released here https://www.nuget.org/packages/SharpCompress/0.30.0
