### ISSUE TITLE
Search for entries in zip archive

### ISSUE THREAD

**Issue by neumatho** [adamhathcock/sharpcompress#620]
If you open an entry in a zip archive and while you have it opened, search for another entry, the first entry is not complete. Here is an example:

```
using System;
using System.IO;
using System.Linq;
using SharpCompress.Archives.Zip;

namespace Archive
{
	class Program
	{
		static void Main(string[] args)
		{
			using (FileStream fs = new FileStream(@"P:\\m\\rw\\sfx2.angel_harp.zip", FileMode.Open))
			{
				ZipArchive archive = ZipArchive.Open(fs);

				ZipArchiveEntry entry = archive.Entries.FirstOrDefault(e => e.Key == "SOAMC/SOAMC_AMIGA/SoundFX_2.0/Roman_Werner/sfx2.angel_harp");
				using (Stream s = entry.OpenEntryStream())
				{
					ZipArchiveEntry entry1 = archive.Entries.FirstOrDefault(e => e.Key == "SOAMC/SOAMC_AMIGA/SoundFX_2.0/Roman_Werner/sfx2.angel_harp.txt");

					using (MemoryStream ms = new MemoryStream())
					{
						s.CopyTo(ms);
						long len = ms.Length;
					}
				}
			}
		}
	}
}
```

It this case, the len variable is zero, which means nothing has been copied to the MemoryStream. If you uncomment the entry1 search (which do not find anything), then it works fine. Also if I change the entry1 search to search for the same entry (or some other entry that does exists), it also work. It seems to fail, if the search did not find anything.

I have attached the test archive, but I guess you can use any archive.

[sfx2.angel_harp.zip](https://github.com/adamhathcock/sharpcompress/files/7230918/sfx2.angel_harp.zip)

**Comment by adamhathcock** [comment]
Don't do that then.

Opening an entry stream is manipulating the stream's location to read the correct bytes.  The Entries collection is loaded lazily behind the scenes which is also manipulating the stream's location.  Doing both at the same time is bad.

Generally don't do anything else with the archive while using OpenEntryStream until you close it.

**Comment by neumatho** [comment]
Ok, I will then update my code.
