### ISSUE TITLE
Extract splited 7z archive

### ISSUE THREAD

**Issue by tinohager** [adamhathcock/sharpcompress#626]
Hi i have a splited 7z archive with 4 files. I found no example for this case. Is this posible with this library? Is an example available?
Thank you for the great library.

```cs
var files = new string[]
{
    "archive.7z.001",
    "archive.7z.002",
    "archive.7z.003",
    "archive.7z.004"
}

foreach (var file in files)
{
    using var sevenZipArchive = SevenZipArchive.Open(file, new ReaderOptions
    {
        Password = "1234abcd"
    });
}
```

I would have looked for something like this
```
var files = new string[]
{
    "archive.7z.001",
    "archive.7z.002",
    "archive.7z.003",
    "archive.7z.004"
}

using var sevenZipArchive = SevenZipArchive.Open(files, new ReaderOptions
{
     Password = "1234abcd"
});
```

**Comment by adamhathcock** [comment]
Support for split 7z archives isn't implemented.

**Comment by marcussacana** [comment]
I managed to read 7z Files creating a stream that merge multiple streams into a single stream, worked to me at least, check it: https://github.com/marcussacana/DirectPackageInstaller/blob/main/IO/MergedStream.cs
https://github.com/marcussacana/DirectPackageInstaller/blob/bab0b672ab34f0936f297cd48fb372e588b15296/Compression/SharpComp.cs#L62-L86

**Comment by Nanook** [comment]
I've submitted #658 resolves this issue for zip, 7zip, rar, gzip and tar

**Comment by marcussacana** [comment]
> I've submitted #658 that resolves this issue for zip, 7zip, rar, gzip and tar
even zip?! this I loved it!
Works with zip64 as well?

**Comment by adamhathcock** [comment]
Looks like it's split extraction for just about everything.  I'm surprised more changes weren't required.

Thanks @Nanook for the changes.  If you want to be more of a regular contributor/maintainer, we should talk!

**Comment by Nanook** [comment]
Yes I'd be interested. I have other commitments, but I use the project a lot and there are other fixes I'd like to make too. Thanks
