### ISSUE TITLE
Indexed Entry Table

### ISSUE THREAD

**Issue by GihanSoft** [adamhathcock/sharpcompress#628]
Is anyway to save each entry index so app not need to iterate all of archive each time need one of entries?
now I do this:
```csharp
while (reader.MoveToNextEntry() && !reader.Entry.Key.Equals(name, StringComparison.OrdinalIgnoreCase))
{
}
reader.WriteEntryTo(memStream);
``` 

I like something like this:
```csharp
IIndexedEntryTable entryTable = reader.CreateIndexedEntryTable();
entryTable[name].WriteEntryTo(memStream);
```

**Comment by adamhathcock** [comment]
Readers are useful for forward only streams.  If you're iterating over the stream multiple times, then it's probably not a forward-only stream.

Use the Archive interface which indexes entries for random access.

**Comment by GihanSoft** [comment]
Tank you. this lib is really great and helpful.
