### ISSUE TITLE
Support .Net Framework 4.5

### ISSUE THREAD

**Issue by Th3AnG3L** [adamhathcock/sharpcompress#634]
Can someone help how to use the library for .net framework windows forms ?
From nuget i cannot install it. Someone can help ?

**Comment by bannikovilea** [comment]
Hi, you can update your project to .Net Framework 4.8 and use the implementation for the .Net standard2.0

**Comment by adamhathcock** [comment]
No one supports 4.5 anymore https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework
