### ISSUE TITLE
Zip file ArchiveFactory.Open throws exception for Legacy compressed zip file

### ISSUE THREAD

**Issue by Malshan90** [adamhathcock/sharpcompress#644]
Hi, 

The zip file I'm using use Zip 2.0 (Legacy) compression. When I try to open it via ArchiveFactory.Open, I get below exception,
**"Cannot determine compressed stream type. Supported Archive Formats: Zip, GZip, Tar, Rar, 7Zip"**
I'm using ArchiveFactory Open(string filePath, ReaderOptions? options = null) method. All AES encrypted file can be open and extract without any issues.

Could you guide me here, This is the first time we got Legacy files from a client. Thing is we do need to support legacy method in our system as any new client can be sending legacy compressed files.

Thanks in Advance.

**Comment by adamhathcock** [comment]
This would need investigating what Magic Bytes are in the file that are unmatched to what SharpCompress knows about.

Do they work if you use ZipArchive.Open directly?

**Comment by Malshan90** [comment]
Sorry, I found the issue and that was our engineer has used an iteration and instead of directly sending the zip file he's been sending bunch of other files as well. I just reviewed the code and removed the buggy code.
It works perfectly.
Sorry to bother you.
Keep it up the good work.!
