### ISSUE TITLE
Adler32 is AGPL-3.0 licensed

### ISSUE THREAD

**Issue by tngraf** [adamhathcock/sharpcompress#645]
The file Adler32.cs contains the statement "Licensed under the GNU Affero General Public License, Version 3".
Due to the copyleft effect of AGPL-3.0 this will put **ALL code** linked dynamically or statically to this file also under AGPL-3.0.
As far as I can see this would affect *ALL* files of SharpCompress.

AGPL-3.0 is also incompatible to MS-PL and Apache-2.0...

Has all this been considered?

**Comment by adamhathcock** [comment]
You are correct.  This needs to be removed as I just read it and it comes from SixLabers/ImageSharp.

It could be updated to the newer version which is Apache 2.0: https://github.com/SixLabors/ImageSharp/blob/main/src/ImageSharp/Compression/Zlib/Adler32.cs

**Comment by adamhathcock** [comment]
Fix released in https://www.nuget.org/packages/SharpCompress/0.31.0
