### ISSUE TITLE
AddAllFromDirectoryEntry not defined?

### ISSUE THREAD

**Issue by fschwiet** [adamhathcock/sharpcompress#65]
I was using the ZipArchive with Writing example here: https://github.com/adamhathcock/sharpcompress/wiki/API-Examples.  I have the nuget package SharpCompress.0.11.0.

  The code fails to compile, saying AddAllFromDirectoryEntry is not defined.  Is this an extension method in some other namespace/DLL?  I do not know where to find it.

**Comment by adamhathcock** [comment]
What is your platform?  This only works on the full .NET framework:
https://github.com/adamhathcock/sharpcompress/blob/master/SharpCompress/Archive/IWritableArchive.Extensions.cs

**Comment by fschwiet** [comment]
I started the project in Xamarin Studio so initially it ran against
mono.  When I hit the issue I was building the same solution from visual
studio.  Its currently set to build x86.

**Comment by damieng** [comment]
The SDK says "AddAllFromDirectoryEntry" but the actual API is "AddAllFromDirectory" and the file is now at https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Writers/IWriterExtensions.cs

**Comment by damieng** [comment]
Updated the Wiki, can now close this issue.
