### ISSUE TITLE
LinqBridge

### ISSUE THREAD

**Issue by Sinedia** [adamhathcock/sharpcompress#66]
Could LinqBridge be removed? 
It is a dependency on NuGet level that isn't needed, so why make a required reference between the two? If someone wants to use LinqBridge he can add the reference himself and use it. Sounds more logical than getting the reference and having to remove it manually when you don't want to use it... and added to that: when you don't want to use it you are still required to have the NuGet package because the reference is required, even though you are not using it.

**Comment by adamhathcock** [comment]
Isn't it just for .NET 2 in nuget?

**Comment by balticSD** [comment]
No it is a requirment for all Net version. Brings big namespace problems on NET Version > 2.0

**Comment by adamhathcock** [comment]
I'll have to wait until tomorrow to test but nuget.org seems to think it's just .NET 2.0 
http://www.nuget.org/packages/sharpcompress/

I didn't believe the nuspec changed.  Hmm.

**Comment by Sinedia** [comment]
It's what batic said... took me a while to figure out I could fix the issues I had by throwing out the references in code to LinqBridge. But then I still have the reference in NuGet packages which I also would like to dissapear.

And you are right that it is meant for .NET 2.0, but since you referenced it all .net versions are getting it right now and for all newer versions it brings that pesky namespace issue.

**Comment by thegreatco** [comment]
I am currently targeting .NET 4.6 and NuGet is installing LINQBridge. It might just be an error in the packaging metadata, but it is definitely being installed on higher versions than .NET 2.0.

**Comment by adamhathcock** [comment]
I'll probably just remove the .NET 2.0 target.  I don't even want to have to build it anymore.

**Comment by jskeet** [comment]
+1 to removing the dependency. With .NET 4.5 it includes the dependency but works if you remove the reference. With a .NET 3.5 project I couldn't actually get it to work - the binary depended on LinqBridge existing, but with the reference present any LINQ calls in my code became ambiguous. Basically it's more trouble than it's worth :)

**Comment by adamhathcock** [comment]
Now I just had to remove it :)

Released 0.11.1
https://github.com/adamhathcock/sharpcompress/commit/315c138c056d24c7079839846a1a5fb4d131525e

**Comment by jskeet** [comment]
Works like a dream - thanks!
(If you're interested, this is for Noda Time - I can now download and "compile" a tz data release as a tar.gz file straight from the IANA web site. Woot!)

**Comment by adamhathcock** [comment]
Always interested.  Glad it works :)

**Comment by Sinedia** [comment]
Was on a holiday, so haven't checked it yet. But thanks for solving this!
