### ISSUE TITLE
Malformed zip file generated

### ISSUE THREAD

**Issue by aboryczko** [adamhathcock/sharpcompress#666]
Hi,

I'm using salvois/LargeXlsx library for generating Excel files (which are essentialy zip files) that uses this library.
When I try to open a generated file in Excel it says that it's corrupt. If I try to open the file with any unzip tool there are no errors. When I use the built-in ZipArchive class from .NET Core everything works as expected.
I've dug a little  deeper into the files generated by this library and the .NET one I see that every 16 kB I get 5 bytes inputed into the output stream.
I don't know if this is some special marker but Excel doesn't recognize it and it messes up the content for it i.e. instead of 's="0"' i have 's="0 ý€"'.

a simple way to reproduce it:
```csharp
var ms = new MemoryStream();
var zw = new ZipWriter(ms, new ZipWriterOptions(compressionType: CompressionType.Deflate) { DeflateCompressionLevel = CompressionLevel.None });
var payload = new string('\n', 100000);
using (var stream = zw.WriteToStream("test.txt", new ZipWriterEntryOptions()))
using (var streamWriter = new StreamWriter(stream: stream))
{
    streamWriter.Write(value: payload);
}
```
sequences are at offsets: 38, 32811, 65584,98357

Linking salvois/LargeXlsx#9

**Comment by aboryczko** [comment]
I doesn't matter which level I choose, the issue is the same Excel recognizes the file as corrupt. I've used none in the examples because it is easier to find which characters are causing the issue.

**Comment by Erior** [comment]
Is there any tests in LargeXlsx when dumped to disk that shows the problem, could help me with understanding the problem/corruption, I guess right now I'm totally missing it.

**Comment by Erior** [comment]
Thank you, that does make excel unhappy, I will investigate

**Comment by aboryczko** [comment]
@Erior sorry, I don't follow, could you explain a bit more how can I do it?

**Comment by Erior** [comment]
Top of my head would be for you to build with the pull request changes and use that dll, or wait for @adamhathcock to accept the change and generate new release. Not sure if you can get binaries out from pull builds even though they are tested automatically.
Someone could build it for you and send dll's, that is however a matter of trust/security.
Perhaps Mr Hathcock knows of other options, I participate somewhat infrequently on github.

**Comment by adamhathcock** [comment]
thanks for the fix @Erior 

I'll push out the change soon as it was creating bad files.

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/SharpCompress/0.32.1

**Comment by salvois** [comment]
Hi @aboryczko , @Erior , @adamhathcock ,
SharpCompress 0.32.1 appears to fix the offending code posted above as per in [salvois/LargeXlsx#9](https://github.com/salvois/LargeXlsx/issues/9).
Many thanks for reporting and fixing this!
   Salvo

**Comment by adamhathcock** [comment]
🥳

**Comment by Nanook** [comment]
I'm closing this issue after confirming it's now working.
