### ISSUE TITLE
RAR archives - Cannot get volume number

### ISSUE THREAD

**Issue by lchegde** [adamhathcock/sharpcompress#677]
Is it possible to read the internal volume number for each file in a multi volume archive?
I cannot find this information for RarArchive presently, is this information available using sharpCompress?

If not, is this something that could be supported?

Example from `rar.exe ls`, showing the volume number in question for a couple of volume files in the same archive:

```
Archive: <rar-file first volume>
Details: RAR 5, volume 1

 Attributes      Size     Date    Time   Name
----------- ---------  ---------- -----  ----
 -rw-r--r--   1161022  2022-04-24 07:12  filename.jpg
 -rw-r----- 1641030031  2022-04-24 07:10  filename.mp4
----------- ---------  ---------- -----  ----

Archive: <rar-file second volume>
Details: RAR 5, volume 2

 Attributes      Size     Date    Time   Name
----------- ---------  ---------- -----  ----
 -rw-r----- 1641030031  2022-04-24 07:10  filename.mp4
----------- ---------  ---------- -----  ----

````

**Comment by adamhathcock** [comment]
it's possible but it's not that simple.  An entry can be spread across multiple volumes.  The data is in the FilePart classes and could be exposed somehow: https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Common/Rar/RarFilePart.cs

**Comment by Nanook** [comment]
https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Common/IEntry.cs

Now has the first and last volume index. This index can be used to get the files filenames using archive.Volumes[index].FileName
