### ISSUE TITLE
exception question

### ISSUE THREAD

**Issue by ghostriderinthesky** [adamhathcock/sharpcompress#678]
Hi

When trying to open some RAR files, I get more exceptions and would like to ask what they mean. Are it maybe corrupted archives too?
WinRAR gives error messages too on those files.

- SharpCompress.Common.InvalidFormatException
Message: Unknown Rar Header: (followed by a number)

- System.InvalidOperationException
Message: Cannot determine compressed stream type. Supported Archive Formats: Zip, GZip, Tar, Rar, 7Zip

Is there a way I can fix RAR files using a tool? Or is the only way to get rid off those exceptions by extracting the content files that still can be extracted from the RAR file and then make a new RAR file with the extracted files?

Thank you!

**Comment by adamhathcock** [comment]
The errors are trying to be descriptive about what's wrong so that should help you to diagnose the issues.  

What you to do try to fix things is up to you.  Sorry, but I'm not WinRAR support.
