### ISSUE TITLE
Windows Phone SL 8.1 certification failing

### ISSUE THREAD

**Issue by scpc0609** [adamhathcock/sharpcompress#68]
With the latest nuget package 0.11.0 the Windows Phone Silverlight 8.1 certification is failing saying it contains "Debug" version of the sharpcompress,dll. Is it possible to update the nuget package with the "Release" version anytime soon please?

Also it seems that the zip directory listing does not obey the character encoding in the names... how to use UTF8 so that all entry names appear correct?

**Comment by scpc0609** [comment]
I think the issue is too trivial for the developer and hence not fixed yet. Need to find some other library now.

**Comment by adamhathcock** [comment]
The opposite actually.  I don't have time.  You can fix it yourself or use another library.  No need to snooty to free and open source projects.
