### ISSUE TITLE
When using ZipReader to read a streamed zip file, MoveToNextEntry skipping doesn't work properly

### ISSUE THREAD

**Issue by AlexVallat** [adamhathcock/sharpcompress#685]
If using ZipReader to read a streamed zip file (using PostDataDescriptor) then using MoveToNextEntry to skip an entry does not work properly. I think this is because AbstractReader.Skip always sets `filePart.Skipped = true` https://github.com/adamhathcock/sharpcompress/blob/c73a8cb18fa2bffdec01bed3fea397e3bae25acf/src/SharpCompress/Readers/AbstractReader.cs#L135 even if the entry size is not known and so it has to decompress to skip.

Minimal repro:
[test.zip](https://github.com/adamhathcock/sharpcompress/files/9139065/test.zip)
```csharp
using (var fileStream = File.OpenRead("test.zip"))
using (var reader = SharpCompress.Readers.Zip.ZipReader.Open(fileStream))
{
    while (reader.MoveToNextEntry())
    {
        Console.WriteLine(reader.Entry.Key);
        // reader.OpenEntryStream().Dispose(); // Uncomment for workaround
    }
}
```
When run, after the first entry, the next MoveToNextEntry returns false even though there are further entries.
If you uncomment the `reader.OpenEntryStream().Dispose();` line then this has the same effect of skipping the entry, but without setting filePart.Skipped true, and all the entries are listed.

**Comment by AlexVallat** [comment]
Note, this is a regression from 0.32.0 to 0.32.1. Probably due to https://github.com/adamhathcock/sharpcompress/pull/672 ?

**Comment by adamhathcock** [comment]
You're right that PR broke this.  Might have to revert.

Discussion here: https://github.com/adamhathcock/sharpcompress/issues/477

**Comment by Erior** [comment]
I think this should be closed

**Comment by adamhathcock** [comment]
Yup.  0.32.2 fixed this I believe
