### ISSUE TITLE
System.NotSupportedException: 'Specified method is not supported.' On reader.MoveToNextEntry() while decompresing 7z

### ISSUE THREAD

**Issue by GamingCity** [adamhathcock/sharpcompress#734]
Ive been getting this exception when i try to extract a 7zip file, it always start extracting files and get to the same point and throws the exception.

using (var archive = ArchiveFactory.Open("D:\\test.7z"))
{
    var reader = archive.ExtractAllEntries();
    reader.EntryExtractionProgress += Reader_EntryExtractionProgress;
    while (reader.MoveToNextEntry()) <--Exception here
    {
        if (!reader.Entry.IsDirectory)
            reader.WriteEntryToDirectory("D:\\temp", new ExtractionOptions() { ExtractFullPath = true, Overwrite = true });
    }
}
void Reader_EntryExtractionProgress(object? sender, ReaderExtractionEventArgs<IEntry> e)
{
    Console.WriteLine($"{e.Item.Key}: {e.ReaderProgress.PercentageRead} % read, {e.ReaderProgress.PercentageReadExact} % extracted");
}

Im using .net 6.0 on a simple console app.
![image](https://user-images.githubusercontent.com/59067016/224494470-c937843e-d451-426d-8cdb-8059898a0d72.png)

It seems to complain that it cant call reflection from this context, yet i dont understand why it manages to extract half the file before having this problem.

WriteAllToDirectory() also gives this exception.

**Comment by Erior** [comment]
Can be DeltaFilter #726,  do you have the test file somewhere or can you build from this repo and test/report the CMethodId id value when it fails?

**Comment by Shivansps** [comment]
(sorry i posted the issue from the wrong account)
Yeah this is the file, its extensionless but it is a 7z. https://cf.fsnebula.org/storage/38/aa/9cb349c96e4fc0d9e3b88d681642764af71cdf9476a7af6281caafdffafd

**Comment by Erior** [comment]
If you open it in 7z you can see that some entries are using Method Delta:X LZMA, The support for this was added recently and has not yet been released.

**Comment by GamingCity** [comment]
ok if this is fixed on main then ill close this for now.

**Comment by Erior** [comment]
Using the link, it actually fails on a file that 7zip says does not use the delta method, I will see if there are other conditions than the ID for the filter detection

**Comment by Erior** [comment]
and I was wrong, but it looks to be a noop setup, not appying the filter seems to be the right way, I'll look into it some more later

**Comment by Erior** [comment]
From my testing it looks like the check should be removed #735

**Comment by GamingCity** [comment]
Seems to be working fine now, thanks.

**Comment by adamhathcock** [comment]
Thanks both!
