### ISSUE TITLE
TarHeaderFactory Infinite loop

### ISSUE THREAD

**Issue by Ilanlido** [adamhathcock/sharpcompress#736]
A possible Infinite loop can occur,
Let's look at https://github.com/adamhathcock/sharpcompress/blame/master/src/SharpCompress/Common/Tar/TarHeaderFactory.cs#L51
When the stream that is being used has been closed - for example if the connection was cut, it will keep throw an IOException inside https://github.com/adamhathcock/sharpcompress/blame/master/src/SharpCompress/Common/Tar/TarHeaderFactory.cs#L24
And then and infinite loop of nulls will be here 
https://github.com/adamhathcock/sharpcompress/blob/master/src/SharpCompress/Common/Tar/TarEntry.cs#L62

**Comment by adamhathcock** [comment]
PRs are welcome

**Comment by svenclaesson** [comment]
[zoneinfo-2010g.zip](https://github.com/adamhathcock/sharpcompress/files/11418820/zoneinfo-2010g.zip)

This file contains a corrupt tar file that also triggers this infinite loop issue.
