### ISSUE TITLE
SharpCompress 0.34.0 does not have a strong name.

### ISSUE THREAD

**Issue by AptiviCEO** [adamhathcock/sharpcompress#764]
Hello,

First of all, thank you for your efforts at making this library.

As of the recent update that was released an hour long, SharpCompress 0.34.0 wasn't signed with a strong name, which causes every library that are signed with a strong key to emit warnings that say:

```
CS8002: Referenced assembly 'SharpCompress, Version=0.34.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

SharpCompress 0.33.0 didn't emit this warning because it was signed. Also, this signing key change wasn't listed in the changelogs.

What is the cause of the lack of signing? I would like this to be fixed.

Thanks!

**Comment by adamhathcock** [comment]
Must be the new dependency for zstd that prevents it as nothing else has been done to stop strong naming

**Comment by AptiviCEO** [comment]
OK, thanks. However, it looks like that the zstd port is strong named in the project file:

https://github.com/oleg-st/ZstdSharp/blob/master/src/ZstdSharp/ZstdSharp.csproj

**Comment by caesay** [comment]
For now, seems 0.33.0 is the last release that can be used on the full framework because of this issue. 34.0 and 34.1 both fail due to strong name issues. This is not a problem in dotnet (core) because strong names are not checked.

**Comment by AlexVallat** [comment]
Looks like `<SignAssembly>` was changed to `false` in SharpCompress.csproj, but was this deliberate for some reason?

**Comment by adamhathcock** [comment]
Merged that and deployed https://www.nuget.org/packages/SharpCompress/0.34.2 to fix by @caesay

**Comment by AptiviCEO** [comment]
I updated this library and I no longer have this issue. Thanks @adamhathcock and @caesay!
