### ISSUE TITLE
Typo in ArchiveReader.cs will cause build to fail in all configurations except Debug

### ISSUE THREAD

**Issue by haykpetros** [adamhathcock/sharpcompress#78]
If you look at Line 246 in "SharpCompress\Common\SevenZip\ArchiveReader.cs" you will notice extra line that is causing build to fail in any build configuration other than Debug:

```cs
#if DEBUG
                            Log.WriteLine("Complex Stream (In: " + coder.NumInStreams + " - Out: " + coder.NumOutStreams +
#endif
 ")");
                        }
```

So it is necessary to remove Line 246 completely in order to fix this issue.

**Comment by adamhathcock** [comment]
Thanks for this, could you make this a Pull Request by chance?
