### ISSUE TITLE
Problem with Microsoft.SourceLink.GitHub dependency

### ISSUE THREAD

**Issue by bdovaz** [adamhathcock/sharpcompress#838]
It must be added as `PrivateAssets=“All”`. I use the Avalonia repository as an example:

https://github.com/AvaloniaUI/Avalonia/blob/76a1c70758884abcebc9e3665aa08290a841efa4/build/SourceLink.props#L18

As it stands since version 0.37.0 it has a dependency that propagates to consumers of the package when it should not:

https://www.nuget.org/packages/SharpCompress/0.37.0#dependencies-body-tab

**Comment by adamhathcock** [comment]
I never looked that up to see what it did.

I've made the change here: https://github.com/adamhathcock/sharpcompress/commit/1393629bc5db0b806c7033a062670a5bb7a4ae80

Thanks for the heads up

**Comment by bdovaz** [comment]
Can you release it on nuget please? We use this package in Unity and it causes us problems. 

Thanks for your help!

**Comment by adamhathcock** [comment]
Not sure it achieved what you wanted: https://www.nuget.org/packages/SharpCompress/0.37.1

**Comment by adamhathcock** [comment]
real real fix: https://github.com/adamhathcock/sharpcompress/commit/446852c7d0796e7ce375ebf136a05bbda47ee237

The tests no longer reference this package

**Comment by adamhathcock** [comment]
https://www.nuget.org/packages/SharpCompress/0.37.2

**Comment by bdovaz** [comment]
Thank you @adamhathcock for your quick response and release!

**Comment by bdovaz** [comment]
@adamhathcock can you unlist on NuGet 0.37.0 and 0.37.1? Thanks!

So that no one consumes these versions with incorrect dependencies

https://learn.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages#unlisting-a-package

**Comment by bdovaz** [comment]
@adamhathcock can you please hide those 2 versions with the instructions I gave you? It's giving us problems at: https://github.com/xoofx/UnityNuGet

We can't resolve in Unity those incorrect dependencies.

Thank you.

**Comment by adamhathcock** [comment]
unlisted

**Comment by bdovaz** [comment]
Thank you!
