### ISSUE TITLE
security policy

### ISSUE THREAD

**Issue by fuzzah** [adamhathcock/sharpcompress#841]
@adamhathcock please consider adding a security policy.
I have some issues to report which you might want to look into

**Comment by adamhathcock** [comment]
You can report them as issues and/or PRs.  I don't have a policy as I'm just a guy on an open source project

**Comment by fuzzah** [comment]
Being just an open source project guy doesn't stop you from having an email or some other method to contact you for issues which might affect security!
Don't belittle yours and your project's importance for the community :)

**Comment by adamhathcock** [comment]
Thank you but I don't see the need to be secretive I think.  Please make a PR.  Having a way to contact me led to spam :)
