### ISSUE TITLE
Unable to open a certain rar file

### ISSUE THREAD

**Issue by marcussacana** [adamhathcock/sharpcompress#844]
After debug a bit I noticied a exception in the shaprcompress with the message `Invalid StreamingMode`,  
after that the RarArchive.Open returns normally but it says that there are no entries in the compressed file.

I'm using sharpcompress 0.37.2, [sample.rar](https://www.mediafire.com/file/pbhy3et7lk6st9a/sample.rar/file)

**Comment by adamhathcock** [comment]
Thanks for the fix @Erior
