### ISSUE TITLE
`GZipArchive`s created from a stream have `ArchiveType` set to `Tar` instead of `GZip`

### ISSUE THREAD

**Issue by Morilli** [adamhathcock/sharpcompress#845]
Since 61c01ce9b083ed9c23229ee4d75975cfa0aa58e1, `GZipArchive`s created from a source stream get their `ArchiveType` set to `ArchiveType.Tar` instead of `ArchiveType.GZip`.

https://github.com/adamhathcock/sharpcompress/blob/6fc4b045fde70c42df738d203c453082354e9558/src/SharpCompress/Archives/GZip/GZipArchive.cs#L103-L104

This gives an incorrect `ArchiveType` when checking with `ArchiveFactory.Open` for example.

**Comment by adamhathcock** [comment]
A test or PR to fix would be great, thanks!
