### ISSUE TITLE
Problems discovered while decompressing PosrgresSQL

### ISSUE THREAD

**Issue by Cyaim** [adamhathcock/sharpcompress#851]
![image](https://github.com/adamhathcock/sharpcompress/assets/28213262/639dc3a8-98c5-4ca3-97df-9212ee14f1d4)

After using this code to decompress 7z, it was found that the database could not be started.

![image](https://github.com/adamhathcock/sharpcompress/assets/28213262/f3c9daf8-e85f-4437-8e98-2cdab49edf8b)

Then I searched for the reason for the inability to start, which was caused by the lack of an empty directory named pgsql_tmp after decompression.

**Comment by adamhathcock** [comment]
Empty directories missing are a known bug.  This should be fixed

**Comment by alexprabhat99** [comment]
@adamhathcock Can I take this up?

**Comment by adamhathcock** [comment]
@alexprabhat99 please do.  It should be similar for all formats and probably can be implemented for them all at once.

**Comment by alexprabhat99** [comment]
@adamhathcock Please check out PR #857 as a potential fix for the above issue.
