### ISSUE TITLE
Question: Does this have 7zip reader?

### ISSUE THREAD

**Issue by 0x5bfa** [adamhathcock/sharpcompress#867]
I'm finding a room to implement 7zip writer using managed-lzma and during walking through the code base I found 7zip reader while FORMATS.md says N/A

Code was added intially 11 years ago but the table of FORMATS.md updated 2 years ago.

https://github.com/adamhathcock/sharpcompress/blob/8de33f0db3ad09f85fe96e953418935d05186aa6/src/SharpCompress/Archives/SevenZip/SevenZipArchive.cs#L202-L254

https://github.com/adamhathcock/sharpcompress/blob/8de33f0db3ad09f85fe96e953418935d05186aa6/FORMATS.md?plain=1#L21

7zip reader exists or still missing?

**Comment by adamhathcock** [comment]
There is no 7ZipReader interface becase 7Zip doesn't support forward only.  It requires random access to the stream which is against the reader interface.  Internally, 7Zip is made of streams that are forward only

**Comment by 0x5bfa** [comment]
Thanks for the reply and understood.

I have a couple of questions:

- Compression API can still be implemented using managed-lzma? I saw an old issue mentioning this.
- SevenZipSharp supports (if you know) forward only reader and writer? Or does it does random access?

**Comment by adamhathcock** [comment]
I believe we still use the managed LZMA internally.  I don't want native dependencies.

I don't believe anything supports forward only always because it's against the 7Zip spec.  Which is why it's il-suited, imo.  7Zip always wants random access which usually means a file.

**Comment by 0x5bfa** [comment]
I see.
