### ISSUE TITLE
[Question] No more nuget updates?

### ISSUE THREAD

**Issue by marcussacana** [adamhathcock/sharpcompress#869]
The project seems to be alive but it was a good time that the nuget build hasn't updated, there are things to be solved for an update or the nuget support is just dropped?

**Comment by adamhathcock** [comment]
I do a nuget build on an adhoc basis.  Probably time to do another one

**Comment by marcussacana** [comment]
Glad to know, I will be waiting then, thx

**Comment by marcussacana** [comment]
Cool, thanks man
