### ISSUE TITLE
Unknown Rar Header: 45

### ISSUE THREAD

**Issue by majorro** [adamhathcock/sharpcompress#882]
Cannot open [this](https://vk.com/doc15149684_232453494?hash=B4qUwhRvMpFz4kZkDb7EpJ12Eu2Zb0kaQINYOdl4nA0&dl=HNFyE8jQHO8EIcA4Xoo1mgC9vW5swgFTgAPpvbOlOSc) old .rar file with 0.38.0, but it's being opened with no issues with WinRAR 5.80

**Comment by Erior** [comment]
Tested with RarArchive.Open and ArchiveFactory.Open, extracted all files.
We would need more information to reproduce the problem.

**Comment by majorro** [comment]
hmm, now it works for me too, seems like I've done something wrong
