### ISSUE TITLE
RAR archive mistaken as Tar archive

### ISSUE THREAD

**Issue by elgonzo** [adamhathcock/sharpcompress#89]
SharpCompress will not open and read the following RAR file correctly:

RAR file download link:http://wikisend.com/download/295490/RAR_identified_as_Tar.rar
Password: adamhathcock
(**The download link expires after 90 days!**)

The RAR archive is **NOT** in RAR5 format, and it contains only one file "PROTONIX.D64".

*ArchiveFactory.Open(...)* will return a *SharpCompress.Archive.Tar.TarArchive* instance for this RAR file.
And *ReaderFactory.Open(...)* will return a *SharpCompress.Reader.Tar.TarReader*.

SharpCompress version used: 0.11.1

**Comment by elgonzo** [comment]
I guess, the file format check should be changed so that Tar is not tested before other archive formats such as RAR.

In ArchiveFactory: https://github.com/adamhathcock/sharpcompress/blob/master/SharpCompress/Archive/ArchiveFactory.cs#L129
In ReaderFactory: https://github.com/adamhathcock/sharpcompress/blob/master/SharpCompress/Reader/ReaderFactory.cs#L65

**Comment by adamhathcock** [comment]
Did your suggestion: https://github.com/adamhathcock/sharpcompress/commit/21087323af2caa5cfb394eee30ecd919b68421c6
