### ISSUE TITLE
'SharpCompress.Common.IEntry' does not contain a definition for 'FilePath'

### ISSUE THREAD

**Issue by hkazaz** [adamhathcock/sharpcompress#95]
version  0.11.1 from Nuget is installed in vs2012 and project's target framework is 4.0.

When compiling, it gives :

Error	 23934	
'SharpCompress.Common.IEntry' 
does not contain a definition for 'FilePath' and 
no extension method 'FilePath' accepting a first argument of type 
'SharpCompress.Common.IEntry' could be found (are you missing a using directive or an assembly reference?)	
fyi.

**Comment by mj1856** [comment]
I believe it was renamed to `Key` in https://github.com/adamhathcock/sharpcompress/commit/66ffc82d41ff6faa22c89b85d7d74bfd0d59d8f7
